<?php $this->headScript()->appendFile('/controllers/admin/js/searchtaxis.js') ?>  	
    <!-- block -->
    <div class="block">
        <div class="block-content collapse in">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                    <thead>
                        <tr>
                        	<th>Modelo</th>
                            <th>Marca</th>
                            <th>Placas</th>
                            <th>ECO</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>                                
                        <?php foreach($this->dataTable as $key => $items): ?>  
                        <tr class="odd gradeX">
                            <td><?php echo $items['MODELO_NAME']; ?></td>
                            <td><?php echo $items['MARCA_NAME']; ?></td>
                            <td><?php echo $items['PLACAS']; ?></td>
                            <td><?php echo $items['ECO']; ?></td>
                            <td class="text-center">                                
                                <a href="javascript:parent.assignValue('<?php echo $items['ECO']."-".$items['PLACAS']; ?>',<?php echo $items['ID_TAXI'];?>)"><button class="btn-flat btn-primary"> <i class="fa fa-arrow-right"></i></button></a>
                            </td>
                        </tr>    
                        <?php endforeach;?>                                             
                    </tbody>
                </table>
        </div>
    </div>
    <!-- /block -->