<?php $this->headScript()->appendFile('/controllers/admin/js/jsValidateRates.js') ?>
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>
<input id="hRefLinkMain" type="hidden" value="/finances/clases/index" />
<section class="content">
    <div id="divAlert" class="alert alert-danger alert-dismissable hide">
        <i class="fa fa-ban"></i>
        <b>!Atención¡</b>
        <div id="divErrorContent">                
        </div>
    </div>

    <div class="col-xs-12">
        <div class="box box-primary row-min-h550">
            <div class="box-header">
                <h3 class="box-title">
                    <a class="pull-left" href="/finances/rates/index">
                        <i class="fa fa-arrow-circle-left"></i> Regresar
                    </a> &nbsp;&nbsp;&nbsp;
                    Información de la Tarifa</h3>
            </div>

            <div class="box-body">
                <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
                    <li class="<?php echo (!isset($this->sOperation) || @$this->resultOp=='okRegister') ? 'active': ''; ?>"><a href="#table" data-toggle="tab" aria-expanded="true">Información General</a></li>
                    <li class="<?php echo (isset($this->sOperation) && @$this->resultOp=='okRegisterTarifas') ? 'active': ''; ?>" style="display:<?php echo (@$this->catId==-1) ? 'none':'block';?>"><a href="#tarifas" data-toggle="tab" aria-expanded="true">Zonas</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane <?php echo (!isset($this->sOperation) || @$this->resultOp=='okRegister') ? 'active': ''; ?>" id="table">

                        <?php if(@$this->resultOp=='okRegister'):?>
                            <div class="alert alert-success alert-dismissable">
                                <i class="fa fa-check"></i>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <b>!Atención¡</b> Los datos se han guardado correctamente.
                            </div>
                        <?php endif;?>         

                        <form role="form" method="POST" action="/finances/rates/getinfo" id="FormData" >
                            <input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
                            <input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />               

                            <div class="col-xs-12">
                                <div class="form-group col-xs-3">
                                    <label for="inputNombre">Descripción</label>
                                    <input type="text" class="form-control upperClass" autocomplete="off" name="inputNombre" id="inputNombre" placeholder="Descripción" value="<?php echo @$this->data['DESCRIPCION']; ?>">
                                </div>
                                <div class="form-group col-xs-3">
                                    <label for="inputClase">Clase de Taxis</label>
                                    <div class="input-group col-xs-12">                     
                                        <select class="form-control" id="inputClase" name="inputClase" >
                                            <option value="">Seleccione una opción</option>
                                            <?php echo $this->aClases;?>                                
                                        </select>
                                    </div>                            
                                </div>
                                <div class="form-group col-xs-3">
                                    <label for="inputEstado">Estado:</label>
                                    <div class="input-group col-xs-12">                     
                                        <select class="form-control" id="inputEstado" name="inputEstado">
                                            <option value="">Seleccione una opción</option>
                                            <?php echo $this->aEstados;?>                                
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-xs-3">
                                    <label for="inputEstatus">Estatus</label>
                                    <div class="input-group col-xs-12">                     
                                        <select class="form-control" id="inputEstatus" name="inputEstatus" >
                                            <option value="">Seleccione una opción</option>
                                            <?php echo $this->aStatus;?>                                
                                        </select>
                                    </div>
                                </div>                                
                            </div>
                            <div class="col-xs-12">
                                <div class="form-group col-xs-3">
                                    <label for="inputuTaximetro">¿Usa Taximetro?</label>
                                    <div class="input-group col-xs-12">                     
                                        <select class="form-control" id="inputuTaximetro" name="inputuTaximetro" onChange="onChangeTaximetro(this.value)" >
                                            <option value="">Seleccione una opción</option>
                                            <?php echo $this->aTaximetro;?>                                
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-xs-3">
                                   <label for="inputBanderazo">Costo Banderazo ($)</label>
                                    <input type="text" class="form-control upperClass" autocomplete="off" name="inputBanderazo" id="inputBanderazo" placeholder="Costo Banderazo" value="<?php echo @$this->data['BANDERAZO']; ?>">                           
                                </div>
                                <div class="form-group col-xs-3">
                                   <label for="inputHinicio">Horario Inicio</label>
                                    <input type="text" class="form-control upperClass" autocomplete="off" name="inputHinicio" id="inputHinicio" placeholder="Inicio de Horario" value="<?php echo @$this->data['HORARIO_INICIO']; ?>">
                                </div>

                                <div class="form-group col-xs-3">
                                   <label for="inputHfin">Horario Fin</label>
                                    <input type="text" class="form-control upperClass" autocomplete="off" name="inputHfin" id="inputHfin" placeholder="Fin de Horario" value="<?php echo @$this->data['HORARIO_FIN']; ?>">                           
                                </div>
                            </div>

                            <h4 class="optTaximetro">Costos (Si usa taximetro)</h4>
                            <div class="col-xs-12 optTaximetro">
                                <div class="form-group col-xs-4">
                                   <label for="inputMinsCobro">Cobrar cada (mins)</label>
                                    <input type="text" class="form-control upperClass" autocomplete="off" name="inputMinsCobro" id="inputMinsCobro" placeholder="Cobrar cada x minutos" value="<?php echo @$this->data['COSTO_MINUTOS']; ?>">                           
                                </div>
                                <div class="form-group col-xs-4">
                                    <label for="inputKmsCobro">Cobrar cada (kms)</label>
                                    <input type="text" class="form-control upperClass" autocomplete="off" name="inputKmsCobro" id="inputKmsCobro" placeholder="Cobrar cada x kilómetros" value="<?php echo @$this->data['COSTO_KILOMETRO']; ?>">
                                </div>                        
                            </div>                         

                            <h4 class="optTaximetro">Costos Fuera de Horario</h4>
                            <div class="col-xs-12 optTaximetro">
                                <div class="form-group col-xs-4">
                                   <label for="inputMinsFhor">Cobrar cada (mins)</label>
                                    <input type="text" class="form-control upperClass" autocomplete="off" name="inputMinsFhor" id="inputMinsFhor" placeholder="Cobrar cada x minutos" value="<?php echo @$this->data['MIN_FUERA_HORARIO']; ?>">
                                </div>
                                <div class="form-group col-xs-4">
                                    <label for="inputKmsFhor">Cobrar cada (kms)</label>
                                    <input type="text" class="form-control upperClass" autocomplete="off" name="inputKmsFhor" id="inputKmsFhor" placeholder="Cobrar cada x kilómetros" value="<?php echo @$this->data['KM_FUERA_HORARIO']; ?>">
                                </div>                        
                            </div>

                            <h4 class="optTaximetro">Costos Fuera de Zona</h4>
                            <div class="col-xs-12 optTaximetro">
                                <div class="form-group col-xs-4">
                                   <label for="inputMinsFzona">Cobrar cada (mins)</label>
                                    <input type="text" class="form-control upperClass" autocomplete="off" name="inputMinsFzona" id="inputMinsFzona" placeholder="Cobrar cada x minutos" value="<?php echo @$this->data['MIN_FUERA_ZONA']; ?>">                           
                                </div>
                                <div class="form-group col-xs-4">
                                    <label for="inputKmsFzona">Cobrar cada (kms)</label>
                                    <input type="text" class="form-control upperClass" autocomplete="off" name="inputKmsFzona" id="inputKmsFzona" placeholder="Cobrar cada x kilómetros" value="<?php echo @$this->data['KM_FUERA_ZONA']; ?>">
                                </div>                        
                            </div>  


                            <h4 class="optNotaximetro">Costos Fuera de Horario</h4>
                            <div class="col-xs-12 optNotaximetro">
                                <div class="form-group col-xs-4">
                                   <label for="inputCobroFhor">Costo </label>
                                    <input type="text" class="form-control upperClass" autocomplete="off" name="inputCobroFhor" id="inputCobroFhor" placeholder="Costo Fuera de Horario" value="<?php echo @$this->data['COSTO_FUERA_HORARIO']; ?>">                           
                                </div>                                                   
                            </div>    

                            <div class="form-group">
                              
                            </div>
                            <div class="box-footer">
                                <div class="pull-right">
                                    <button type="button" class="btn margin-5" onClick="javascript:backToMain()">Cancelar</button>
                                    <button type="submit" class="btn btn-primary margin-5">Guardar</button>
                                </div>
                              </div>
                        </form>                           
                    </div>
                    <div class="tab-pane <?php echo (isset($this->sOperation) && @$this->resultOp=='okRegisterTarifas') ? 'active': ''; ?>" id="tarifas" style="display:<?php echo (@$this->catId==-1) ? 'none':'block';?>">
                        <?php //if(@$this->data['USA_TAXIMETRO']==1 && count($this->aTableZonas)==0):?>
                            <div class="pull-right p-10">
                                <a href="/finances/zones/getinfo?catIdtar=<?php echo @$this->catId;?>&catId=-1"><button class="btn btn-success"><i class="fa fa-plus"></i> Agregar</button></a>            
                            </div>
                        <?php //endif;?>                        
                        <table id="dataTableTar" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <!--<th>Por Default</th>    -->       
                                    <th>Descripción</th>
                                    <th>Costo</th>                                    
                                    <th>Costo Acumulable</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($this->aTableZonas as $key => $items): ?>  
                                <tr class="odd gradeX">   
                                    <!--<th>Por Default</th>    -->       
                                    <td><?php echo $items['DESCRIPCION']; ?></td>
                                    <td><?php echo "$ ".number_format($items['COSTO']); ?></td>                                    
                                    <td><?php echo $items['N_ACUM']; ?></td>                                    
                                    <td class="text-center" style="width:100px;">
                                        <?php if($this->dataUser['LECTURA']==1): ?>
                                            <a href="/finances/zones/getinfo?catIdtar=<?php echo @$this->catId;?>&catId=<?php echo $items['ID_ZONA']; ?>"><button class="btn btn-primary"> <i class="fa fa-eye"></i></button></a>   
                                        <?php endif;?> 
                                    </td>
                                </tr>    
                                <?php endforeach;?>                        
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div><!-- /.box -->
    </div>
</section><!-- /.content -->