<style type="text/css">
#slide2{
	background-color: #BDBFC1;
	color: #363C44;
	height: 550px;
}
.backg2{
	background-color:#E4E6E5;
	/*background-color:#869F87;*/
	/*background-image:url('../images/backgrounds/pet-background1.jpg'); opacity: 1;*/
}
#slide2 h1 {
	font-size: 3.8em;
	letter-spacing: -3px;
	line-height: 0px;
	color:#91C713;
	font-weight: 700;
	/*text-shadow: 0.1em 0.1em #333;*/
}

.inside-s2{
	background-color: #FF0000;
	height: 100%;
	left: 5%;
	position: relative;
	width: 90%;
	top: 70px;
}
.sl2-tittle{
	bottom: 15px;
	font-size: 35px;
	font-weight: normal;
	position: relative;
	top: 20px;
	left: 5%;
}
.sl2-container{
	position: relative;
	top: 50px;
	width: 100%;
}
.sl2-left-side{
	float: left;
	width: 50%;
}
.sl2-img{
	left: 10%;
	position: relative;
	top: 15%;
}
.sl2-right-side{
	position: relative;
	top: 15%;
	width: 45%;
	float: left;
}
.sl2-p{
	font-size: 20px;
}
</style>
<div class="slide" id="slide2" data-slide="2" data-stellar-background-ratio="0.5">
	<div class="inside-s2">
		<div class="sl2-tittle">¿Qué es Taccsi?</div>	
		<div class="sl2-container">
			<div class="sl2-left-side">
				<img class="sl2-img" src="/images/assets/img-function.png">
			</div>
			<div class="sl2-right-side">
				<p class="sl2-p"> 
					Taccsi es el conjunto de aplicaciones móviles y web rápidas, intuitivas y eficientes por medio de las cuales ofrecemos un servicio de transporte seguro.
					<br>
					En Taccsi están registrados únicamente vehículos que cubren las normas legales, mecánicas y de seguridad necesarias para realizar travesías sin inconvenientes. Además, todos los vehículos cuentan con la instalación de rastreo satelital que Grupo UDA ha desarrollado por más de 15 años
					<br>			
					Taccsi cuenta con las aplicaciones de la más alta calidad para ofrecer el servicio desde la página web, las Apps instaladas en su dispositivo móvil o vía telefónica.
				</p>
			</div>			
		</div>
	</div>			
</div>