<style type="text/css">
	/* Slide 1 */ 

	#slide4{
		/*background-image:url('../images/backgrounds/background.png');*/
		background-color:#BDBFC1;
		color:#BDBFC1;
		background-size: 100% 100%;	

	;}
	#slide4 h1 {
		color: #F1C000;
		font-size: 30px;
	}
	#slide4 h2 {
		/*font-size: 2em;
		color: #FFFFFF;
		line-height: 0px;
		padding-bottom:20px;
		font-weight: 400;
		text-shadow: 0.1em 0.1em #333;	*/
	}
	#slide4 .container{
		position: absolute;
		top: 15%;
		height: 100%;
		margin: 5% 60%;
		width: 35%;
	}
	#slide4 p{
		/*width: 325px;
		height: 200px;
		text-shadow: 0.1em 0.1em #333;*/
	}
	.inside-slide{
		background-color: #FFFFFF;
		height: 90%;
		left: 5%;
		position: relative;
		top: 15px;
		width: 90%;
		border-radius: 10px;
	}
	.inside-left{
		float: left;
		width: 60%;
		/*background-color: red;*/
		height: 100%;
	}
	.inside-right{
		float: left;
		width: 35%;
		/*background-color: black;*/
		height: 100%;
	}


.contact-us #content.site-width, .error404 #content.site-width {
    color: #545454;
    overflow: auto;
    padding: 2em 0 4em;
}
.site-width {
    margin: 0 auto;
    max-width: 1085px;
    width: 100%;
}
.contact-us #primary .left, .error404 #primary .left {
    padding-right: 5%;
    width: 65%;
}
.entry-header, .entry-content, .entry-summary, .entry-meta {
    max-width: 1150px;
}
.left {
    float: left;
}

.contact-us #primary h2, .error404 #primary h2 {
    color: #545454;
    margin-top: 0;
    text-align: left;
}

.contact-us #primary .right, .error404 #primary .right {
    border-left: 1px solid #D9D9D9;
    font-size: 1.25em;
    text-align: center;
    width: 30%;
}
.right {
    float: right;
}
.contact-us #primary h3, .error404 #primary h3 {
    color: #898989;
    font-family: "Source Sans Pro",Helvetica,sans-serif;
    font-size: 0.75em;
    font-weight: 600;
    line-height: 1;
    margin: 0 0 1em;
    text-align: center;
}
a, .entry-content a {
    color: #4B76E8;
    text-decoration: none;
}
.contact-us #primary .right > div.middle, .error404 #primary .right > div.middle {
    border-bottom: 1px solid #D9D9D9;
    border-top: 1px solid #D9D9D9;
}
.contact-us #primary .right > div, .error404 #primary .right > div {
    padding: 3em 0;
}
.contact-us #primary .right .info-block.social ul, .error404 #primary .right .info-block.social ul {
    margin: 0 auto;
    padding: 0;
    width: 240px;
}
.contact-us form #sf_email, .contact-us form .w2linput.textarea, .error404 form #sf_email, .error404 form .w2linput.textarea {
    width: 70%;
}
.contact-us form .w2linput.text, .error404 form .w2linput.text {
    width: 70%;
}
.contact-us form .w2linput.text, .contact-us form .w2linput.textarea, .error404 form .w2linput.text, .error404 form .w2linput.textarea {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background: none repeat scroll 0 0 #EAEAEA;
    border-color: -moz-use-text-color -moz-use-text-color #C0C0C0;
    border-image: none;
    border-style: none none solid;
    border-width: medium medium 1px;
    padding: 0.5em;
}
.contact-us form input, .contact-us form textarea, .error404 form input, .error404 form textarea {
    margin-bottom: 1em;
}

.contact-p{
	width: 100%;
}

.block-social{
	width: 100%;
}
.block-social ul{
	list-style-type: none;
	height: 80px;
	width: 663px;
	margin: auto;
}
.block-social ul li{
	float: left;
}

.contact-us form .w2llabel.textarea, .error404 form .w2llabel.textarea {
    display: inline;
}
.contact-us form .w2llabel.text, .contact-us form .w2llabel.textarea, .error404 form .w2llabel.text, .error404 form .w2llabel.textarea {
    color: #898989;
    display: block;
    font-family: "Source Sans Pro",Helvetica,sans-serif;
    font-size: 0.66em;
    text-transform: uppercase;
}

</style>
<div class="slide" id="slide4" data-slide="4" data-stellar-background-ratio="0.5">
	<div class="inside-slide">


<div role="main" class="site-content site-width" id="content">		
			<div class="contact-us entry-content left contact-col inside-left" style="height: 100%;">	
				<h2>Contactanos </h2>
				<p class="contact-p">Si tienes alguna duda sobre cómo funciona nuestra aplicación de taxi o  deseas ponerte en contacto con nosotros, envía un mensaje completando el siguiente formulario:</p>

				<div class="salesforce_w2l_lead">
					<form action="#salesforce_w2l_lead_1" method="post" class="w2llead" id="salesforce_w2l_lead_1">
					<div class="sf_field sf_field_first_name sf_type_text">	<label for="sf_first_name" class="w2llabel text">Nombre Completo: <sup><span class="required">*</span></sup></label>
						<input type="text" name="first_name" class="w2linput text" id="sf_first_name" value="">

					</div><div class="sf_field sf_field_last_name sf_type_text">	<label for="sf_last_name" class="w2llabel text">E-mail: <sup><span class="required">*</span></sup></label>
						<input type="text" name="last_name" class="w2linput text" id="sf_last_name" value="">

					</div><div class="sf_field sf_field_company sf_type_text">	<label for="sf_company" class="w2llabel text">Teléfonos:</label>
						<input type="text" name="company" class="w2linput text" id="sf_company" value="">

					</div><div class="sf_field sf_field_description sf_type_textarea">	<label for="sf_description" class="w2llabel textarea">Mensaje:</label>
						<br>
						<textarea name="description" class="w2linput textarea" id="sf_description"></textarea>

					</div>	<input type="text" style="display: none;" value="" class="w2linput" name="message">
						<input type="hidden" value="1" class="w2linput" name="form_id">
						<div class="w2lsubmit"><input type="submit" value="Submit" class="w2linput submit" name="w2lsubmit">
					</div></form>
					<!--<p id="requiredfieldsmsg" class="sf_required_fields_msg"><sup><span class="required">*</span></sup> These fields are required.</p></div>-->
					<p>&nbsp;</p>
			</div><!-- .entry-content -->
		</div>
			<div class="right contact-col inside-right" style="height: 100%;">
			<div>
        		<h3>Teléfonos</h3>
				Área metropolitana:  (55) 5562.0772<br>
				Interior de la República: 01 800 20 TACCSI<br>
				Servicio al Cliente: (55) 5374.9320
			</div>
			<div class="middle">
				<h3>E-mail</h3>
				Soporte Técnico: <a href="mailto:soporte@taccsi.com.mx">soporte@tacssi.com.mx</a><br>
				Servicio al Cliente: <a href="mailto:servicioalcliente@tacssi.com.mx">servicioalcliente@tacssi.com.mx</a>
			</div>
			<div>
				<h3>Siguenos</h3>

				<div class="block-social">
					<ul>
						<li><a href="" target="_blank"><i class="icon-2x icon-facebook-sign"></i></li>
						<li><a href="" target="_blank"><i class="icon-2x icon-twitter-sign"></i></li>
						<li><a href="" target="_blank"><i class="icon-2x icon-youtube-sign"></i></li>
					</ul>
				</div>
				</div>
			</div>
		</div>



	</div>
</div>