<?php $this->headScript()->appendFile('/controllers/callcenter/services/js/scripts.js') ?>
    <section class="content row-min-h500">
        <div class="col-xs-12">
            <div class="box row-min-h500">
                <div class="box-header">
                    <h3 class="box-title">Clientes con el mismo número</h3>
                </div>
                <div class="box-body table-responsive">                                    
                    <table id="tableCLients" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Ap. Paterno</th>
                                <th>Ap. Materno</th>
                                <th>Telèfono</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody> 
                            <?php foreach(@$this->aDataTable as $key => $items): ?>                              
                                <tr>
                                    <td><?php echo $items['NAME'];?></td>
                                    <td><?php echo $items['APP'];?></td>
                                    <td><?php echo $items['APM'];?></td>
                                    <td><?php echo $items['TELEFONO'];?></td>
                                    <td><button type="button" class="btn btn-primary" onClick="getToServicio(<?php echo $items['ID_SRV_USUARIO'];?>)"> 
                                        <i class="fa fa-arrow-circle-right"></i> </button></td>
                                </tr>                                
                            <?php endforeach;?>
                        </tbody>

                        <tfoot></tfoot>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </section><!-- /.content -->