<?php $this->headScript()->appendFile('/controllers/callcenter/services/js/scripts.js') ?>
<aside class="right-side">
    <section class="content">
        <div id="divAlert" class="alert alert-danger alert-dismissable hide">
            <i class="fa fa-ban"></i>
            <b>!Atención¡</b>
            <div id="divErrorContent">                
            </div>
        </div>

        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Búsqueda de Clientes</h3>
                    <div class="pull-right">
                        <button onClick="goToSetClient();" id="btnSearch" type="button" class="btn btn-success">
                            <i class="fa fa-plus-square"></i> Nuevo Cliente</button>
                    </div>                       
                </div><!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="POST" action="/callcenter/main/index" id="FormData">
                    <input type="hidden" name="optReg" value="search" />
                    <input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />

                    <div class="box-body">                                          
                        <div class="form-group col-xs-3">
                            <label for="inputFindName">Nombre</label>
                            <input type="text" class="form-control" name="namefilter" id="inputFindName" placeholder="Nombre" value="<?php echo @$this->aData['namefilter']; ;?>">
                        </div>
                        <div class="form-group col-xs-3">
                            <label for="inputFindApp">Apellido Paterno</label>
                            <input type="text" class="form-control" name="appfilter"  id="inputFindApp" placeholder="Apellido Paterno" value="<?php echo @$this->aData['appfilter']; ;?>">
                        </div>                                                                                                                                              
                        <div class="form-group col-xs-3">
                            <label for="inputFindApm">Appelido Materno</label>
                            <input type="text" class="form-control" name="apmfilter"  id="inputFindApm" placeholder="Appelido Materno" value="<?php echo @$this->aData['apmfilter']; ;?>">
                        </div>
                        <div class="form-group col-xs-3">
                            <label for="inputFindNumber">Nùmero Telefónico</label>
                            <input type="text" class="form-control" name="telfilter"  id="inputFindNumber" placeholder="Nùmero Telefónico" value="<?php echo @$this->aData['telfilter'];?>">
                        </div>
                    </div>

                    <div class="box-footer">
                        <button id="btnSearch" onClick="validateForm()" type="button" class="btn btn-primary">
                            <i class="fa fa-search"></i>  Buscar</button>
                    </div>
                </form>
            </div>

            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Resultados de la Búsqueda</h3>  
                    <!--<div class="pull-right">
                        <button onclick="location.href='/callcenter/services/createclient'" id="btnSearch" type="button" class="btn btn-success">
                            <i class="fa fa-plus-square"></i> Nuevo Cliente</button>
                    </div>-->                                 
                </div>
                <div class="box-body table-responsive">                                    
                    <table id="tableCLients" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Ap. Paterno</th>
                                <th>Ap. Materno</th>
                                <th>Telèfono</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody> 
                            <?php foreach(@$this->aDataTable as $key => $items): ?>                              
                                <tr>
                                    <td><?php echo $items['NAME'];?></td>
                                    <td><?php echo $items['APP'];?></td>
                                    <td><?php echo $items['APM'];?></td>
                                    <td><?php echo $items['TELEFONO'];?></td>
                                    <td><button type="button" class="btn btn-primary" onClick="getToServicio(<?php echo $items['ID_SRV_USUARIO'];?>)"> 
                                        <i class="fa fa-arrow-circle-right"></i> </button></td>
                                </tr>                                
                            <?php endforeach;?>
                        </tbody>

                        <tfoot></tfoot>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->

<!-- COMPOSE MESSAGE MODAL -->
<div class="modal fade" id="ModalConfirm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Usuario no Existe</h4>
            </div>
                <div class="modal-body">
                    <div class="col-xs-offset-2" style="height: 50px;">
                        <button onClick="goToSetClient();" type="button" class="btn margin btn-success pull-left" data-dismiss="modal">Registrar Nuevo Cliente</button>
                        <button class="btn btn-primary margin pull-left" data-dismiss="modal">Buscar Otro Cliente</button>
                    </div>
                </div>
                <div class="modal-footer clearfix">                     
                    <!--<button type="button" class="btn btn-primary pull-left" data-dismiss="modal">Buscar Otro Cliente</button>-->
                </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->