<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Taccsi - Bienvenido</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="/dist/css/AdminLTE.css" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins 
         folder instead of downloading all of them to reduce the load. -->
    <link href="/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
    <link href="/dist/css/skins/skin-yellow.css" rel="stylesheet" type="text/css" />
    <link href="/css/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />        
    <!-- fullCalendar -->
    <link href="/css/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="/css/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
    <link href="/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">      
    <link type="text/css" href="/css/bootstrap-timepicker.min.css" />
    <link href="/css/style.css" rel="stylesheet" type="text/css" />    
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="skin-yellow fixed">
    <div class="wrapper">      

        <?php if(!isset($this->header)):?>
          <?php echo $this->render('admin_header.phtml', 
                                        array (
                                          'dataUser'    => $this->dataUser,
                                        )); ?>
        <?php endif;?>    

        <div class="content-wrapper  <?php echo (!isset($this->header))? '':'margin-l0'; ?> ">
          <?php echo $this->layout()->content; ?>
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <?php echo $this->partial('admin_footer.phtml') ?>

    </div><!-- ./wrapper -->

    <!-- jQuery 2.1.3 -->
    <script src="/plugins/jQuery/jQuery-2.1.3.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- SlimScroll -->
    <script src="/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>    
    <!-- FastClick -->
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.js" type="text/javascript"></script>
    <!-- AdminLTE for demo purposes -->
    <!--<script src="/dist/js/demo.js" type="text/javascript"></script>-->
    <script src="/js/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
    <script src="/js/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
    <script type="text/javascript" src="/js/jquery-validation/dist/jquery.validate.min.js"></script>       

    <!-- InputMask -->
    <script src="/js/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
    <script src="/js/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="/js/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>         
    <script src="/js/bootstrap-datetimepicker.min.js"></script> 
    <script src="/js/plugins/timepicker/bootstrap-timepicker.min.js"></script> 
    <script type="text/javascript" src="/libs/js/jchartfx.system.js"></script>
    <script type="text/javascript" src="/libs/js/jchartfx.coreVector.js"></script> 
    <script type="text/javascript" src="/libs/js/jchartfx.animation.js"></script>
    <script type="text/javascript" src="/libs/js/jchartfx.coreVector3d.js"></script>    
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
        <?php echo $this->headScript() ?>  
  </body>
</html>
