<!--



AMarillo
FED600

Gris
FEFEFE

rojo
ED3237

Amarillo fuerte 
F1C000

Gris 3
BDBFC1

#727376

#F4F4F4

#BDBFC1

-->

<header class="global-header js-global-header" style="position: fixed; top: 0px;">
  <!--<div class="pull-left">
    <a href="#" class="menu js-menu">
      <span class="icon-menu"></span>
      <span class="menu-text res-s-hidden">Menú</span>
    </a>
  </div>-->

  <p class="pull-right actions res-s-hidden">
        <a href="/log-in" class="ga-click-track" data-ga="global-header.login-button-click">
          Iniciar sesión
        </a>
      
      <a href="/sign-up" class="btn ga-click-track js-signup-or-dl-cta js-signup-btn" data-ga="global-header.sign-up-button-click">
        Regístrate
      </a>
    
  </p>
  <p class="pull-right actions res-m-hidden res-l-hidden">
    <a href="/app" class="btn ga-click-track js-signup-or-dl-cta js-signup-btn" data-ga="global-header.download-mobile">
        Descargar
    </a>
  </p>

  <div class="yui3-u-1-3 center block-center">
    <a href="/" class="uber-logo ir ga-click-track" data-ga="global-header.logo-click">taccsi</a>
  </div>

</header>