<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Taccsi - Inicio de Sesión</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="/dist/css/AdminLTE.css" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="/plugins/iCheck/square/blue.css" rel="stylesheet" type="text/css" />
    <link href="/css/style.css" rel="stylesheet" type="text/css" />    

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login-page">
    <div class="login-box">
        <div class="login-logo">
          <a href="/">
              <img src="/images/assets/icon-page.png" class="img-responsive center-block" alt="Logo">
          </a>
        </div><!-- /.login-logo -->              
      <div class="login-box-body box_body_login">
        <p class="login-box-msg">Inicia Sesión</p>
        <div id="div-msgError" class="alert alert-danger alert-dismissable" style="display:none;">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-ban"></i> ¡Error!</h4>
            <div id="div-msg" ></div>
        </div>      
        <form  method="post">
          <div id="formg-user" class="form-group has-feedback">
            <label  id="lbl_user"  class="control-label" for="txt-user"  style="display:none"><i class="fa fa-times-circle-o"></i>Usuario requerida</label>
            <input type="text" class="form-control" id="txt-user"  name="userid"  placeholder="Usuario (E-mail)"/>
            <span class="glyphicon glyphicon-envelope form-control-feedback margin-top-0"></span>
          </div>
          <div id="formg-pass" class="form-group has-feedback">
            <label id="lbl_pass"  class="control-label" for="txt-pass" style="display:none"><i class="fa fa-times-circle-o"></i>Contraseña requerida</label>
            <input id="txt-pass"  type="password" name="password" class="form-control" placeholder="Contraseña"/>
            <span class="glyphicon glyphicon-lock form-control-feedback margin-top-0"></span>
          </div>
          <div class="row p-10">
            <div class="col-xs-12">    
              <!--
                <a class="a_yellow  pull-right" href="/login/main/recovery">Recuperar Contraseña</a><br>
              -->
            </div><!-- /.col -->

          </div>
          <div class="row  p-10">
            <div class="col-xs-12">
              <button  onclick="validatelogin();"  type="button" class="btn btn-primary btn-block btn-flat btn_yellow">Ingresar</button>
            </div><!-- /.col -->            
          </div>
        </form>
      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

    <!-- jQuery 2.1.3 -->
    <script src="/plugins/jQuery/jQuery-2.1.3.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>    
    <script src="/controllers/login/js/login_contact.js" type="text/javascript"></script>    
  </body>
</html>