<!DOCTYPE html>
<html lang="en">
    
    <head>
        <meta charset=utf-8>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>TACCSI</title>

        <meta name="Keywords" content="app de taxis,app de taxi,app para taxi,chofer para taxi,choferes über,uber,easytaxi,yaxi,aplicaciones de taxis,aplicación para taxis,aplicación taxi,taxis über,radio taxis,uber taxis,radio taxi,easy taxi mexico,easy taxi tarifas,taxis,Taccsi,taxi mexico"/>
        <meta name="Description" content="TACCSI es una plataforma integral que utiliza lo último en tecnología con el objetivo de ofrecer un servicio de transporte seguro y a la vanguardia."/>
        <meta name="Distribution" content="global"/>
        <meta name="Robots" content="all"/>            
        <!-- Load Roboto font -->
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <!-- Load css styles -->
        <link rel="stylesheet" type="text/css" href="/branding/css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="/branding/css/bootstrap-responsive.css" />
        <link rel="stylesheet" type="text/css" href="/branding/css/style.css" />
        <link rel="stylesheet" type="text/css" href="/branding/css/pluton.css" />
        <!--[if IE 7]>
            <link rel="stylesheet" type="text/css" href="/branding/css/pluton-ie7.css" />
        <![endif]-->
        <link rel="stylesheet" type="text/css" href="/branding/css/jquery.cslider.css" />
        <link rel="stylesheet" type="text/css" href="/branding/css/jquery.bxslider.css" />
        <link rel="stylesheet" type="text/css" href="/branding/css/animate.css" />
        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/branding/images/ico/apple-touch-icon-144.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/branding/images/ico/apple-touch-icon-114.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/branding/images/apple-touch-icon-72.png">
        <link rel="apple-touch-icon-precomposed" href="/branding/images/ico/apple-touch-icon-57.png">
        <link rel="shortcut icon" href="/branding/images/ico/favicon.ico">
        <link href="/css/style.css" rel="stylesheet" type="text/css" /> 


    <link href="/coming/tools/style.css" rel="stylesheet" type="text/css" />
    <link href="/coming/tools/960.css"   rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script> 
    <script type="text/javascript" src="/coming/js/cufon-yui.js"></script>
    <script type="text/javascript" src="/coming/js/Clarendon_LT_Std_700.font.js"></script>
    <!--<script type="text/javascript">
        Cufon.replace('h1,h3', {fontFamily: 'Clarendon LT Std', hover:true})
    </script>-->
    </head>
    <body>
    <div id="shim"></div>
    <div id="content">
        <div class="logo_box"><h1><br/><br/></h1>
            <img src="/coming/images/logo_admin.png" width="80%"/>
        </div>          
        <div class="main_box">
            <h2>Próximamente<br/><span>Tomar un taxi, nunca fue tan fácil.</span></h2>
            
            <ul class="info">
                <li>
                    <h3>P</h3>
                    <p>01800 444 82 94<br/>
                        <a style="color:#FFFFFF;" href="mailto:contacto@taccsi.com">contacto@taccsi.com</a>
                    </p>
                </li>
                <li>
                    <h3>A</h3>
                    <p>Carlos Arellano 14, Ciudad Satélite, <br/>Naucalpan Edo. Méx.</p>
                </li>
                <li>
                    <!--
                    <h3>S</h3>
                    <p class="social">
                        <a href="#" class="tw"></a>
                        <a href="#" class="fb"></a>             
                        <a href="#" class="li"></a>
                    </p>-->
                </li>
            </ul>
        </div>
    </div>

    </body>
</html>
