<!DOCTYPE html>
<html lang="en">
    
    <head>
        <meta charset=utf-8>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>TACCSI</title>
        <!-- Load Roboto font -->
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <!-- Load css styles -->
        <link rel="stylesheet" type="text/css" href="/branding/css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="/branding/css/bootstrap-responsive.css" />
        <link rel="stylesheet" type="text/css" href="/branding/css/style.css" />
        <link rel="stylesheet" type="text/css" href="/branding/css/pluton.css" />
        <!--[if IE 7]>
            <link rel="stylesheet" type="text/css" href="/branding/css/pluton-ie7.css" />
        <![endif]-->
        <link rel="stylesheet" type="text/css" href="/branding/css/jquery.cslider.css" />
        <link rel="stylesheet" type="text/css" href="/branding/css/jquery.bxslider.css" />
        <link rel="stylesheet" type="text/css" href="/branding/css/animate.css" />
        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/branding/images/ico/apple-touch-icon-144.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/branding/images/ico/apple-touch-icon-114.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/branding/images/apple-touch-icon-72.png">
        <link rel="apple-touch-icon-precomposed" href="/branding/images/ico/apple-touch-icon-57.png">
        <link rel="shortcut icon" href="/branding/images/ico/favicon.ico">
        <link href="/css/style.css" rel="stylesheet" type="text/css" /> 
    </head>
    
    <body>
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <a href="#" class="brand">
                        <img src="/branding/images/logo.png" width="240" height="70" alt="Logo" />
                        <!-- This is website logo -->
                    </a>
                    <!-- Navigation button, visible on small resolution -->
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <i class="icon-menu"></i>
                    </button>
                    <!-- Main navigation -->
                    <div class="nav-collapse collapse pull-right">
                        <ul class="nav" id="top-navigation">
                            <li class="active"><a href="#home">Inicio</a></li>
                            <li><a href="#service">Acerca de Taccsi</a></li>
                            <!--<li><a href="#portfolio">Portfolio</a></li>-->
                            <!--<li><a href="#about">About</a></li>-->
                            <li><a href="#clients">Clientes</a></li>
                            <!--<li><a href="#price">Price</a></li> -->
                            <li><a href="#custom">Quiero ser Taccista</a></li>
                            <li><a href="#contact">Contáctanos</a></li>                            
                            <li><a href="#" onclick="showPanelLogin()">Ingresar</a></li>
                            <li><a href="#" onClick="window.location.href = '/main/registeruser/index';">Registrarme</a></li>
                        </ul>
                    </div>
                    <!-- End main navigation -->
                </div>
            </div>
        </div>
        <!-- Start home section -->
        <div id="home">
            <!-- Start cSlider -->
            <div id="da-slider" class="da-slider">
                <div class="triangle"></div>
                <!-- mask elemet use for masking background image -->
                <div class="mask"></div>
                <!-- All slides centred in container element -->
                <div class="container">
                    <!-- Start first slide--> 
                    <div class="da-slide">
                        <!--<div style="text-align: center; width: 100%; top: 185px; position: relative; color: rgb(254, 206, 26); font-size: 38.5px; /*text-transform: uppercase;*/">
                            Cambiemos juntos la forma de viajar <br/><br/>en TACCSI.
                        </div>-->
                        <h2 class="fittext2"></h2>
                        <h2 style="text-align: center; width: 75%; top: 185px; position: relative; color: rgb(254, 206, 26);">Cambiemos juntos la forma de viajar <br/><br/>en TACCSI.</h2>
                        <!--<p>Somos una empresa que se preocupa por la experiencia del usuario. Nos preocupamos por ofrecer el mejor servicio del mercado. Aplicamos procesos de control a cada unos de nuestros taccsitas, y contamos con la mejor tecnología para que cada viaje sea una experiencia.</p>-->
                        <!--<a href="#" class="da-link button">Read more</a> -->
                        <!--<div class="da-img">
                            <img src="/branding/images/Slider01.jpg" alt="image01" width="320">
                        </div>-->
                    </div>
                    <!-- End first slide-->
                    <!-- Start second slide -->
                    <div class="da-slide">
                        <h2 style="color: rgb(254, 206, 26);">Inovación y Tecnología</h2>
                        <h4 style="color: rgb(254, 206, 26);">Fácil de usar</h4>
                        <p>Mediante la implementación de diversas tecnologías. Puedes solicitar un Taccsi, desde tu smartphone o a través de nuestro Callcenter. Asegurando que siempre tendras un taccsi disponible para tu translado.</p>                        
                        <div class="da-img">
                            <img src="/branding/images/Slider02.png" width="320" alt="image02">
                        </div>
                    </div>
                    <!-- End second slide -->
                    <!-- Start third slide -->
                    <div class="da-slide">
                        <h2 style="color: rgb(254, 206, 26);">Control</h2>
                        <h4 style="color: rgb(254, 206, 26);">Administración de flota</h4>
                        <p>Gracias a nuestra plataforma web. Como dueño de flota, podrá conocer la eficiencia de sus unidades, tener el control de sus viajes y medir el servicio que ofrece a nuestros usuarios. Obtenga el control de su negocio.</p>                        
                        <div class="da-img">
                            <img src="/branding/images/Slider03.png" width="320" alt="image03">
                        </div>
                    </div>
                    <!-- Start third slide -->
                    <!-- Start cSlide navigation arrows -->
                    <div class="da-arrows">
                        <span class="da-arrows-prev"></span>
                        <span class="da-arrows-next"></span>
                    </div>
                    <!-- End cSlide navigation arrows -->
                </div>
            </div>
        </div>
        <!-- End home section -->
        <!-- Service section start -->
        <div class="section primary-section" id="service">
            <div class="container">
                <!-- Start title section -->
                <div class="title" style="border:0px !important;">
                    <h1>Acerca de TACCSI</h1>
                    <div class="span12" style="text-align:left;">
                        <div class="span8">                    
                            <!-- Section's title goes here -->
                            <p>TACCSI es una plataforma integral que utiliza lo último en tecnología con el objetivo de ofrecer un servicio de transporte seguro y a la vanguardia. </p>
                                <p>Cuenta con la infraestructura necesaria para ofrecer el servicio desde la web, aplicaciones móviles iOS y Android y vía telefónica 24/7.                        
                            </p>
                            <p>Todo esto lo logramos gracias al apoyo de Grupo UDA (Tracking Systems) un Corporativo que tiene más de 17 años de experiencia en Rastreo Satelital y líder en dicho mercado por su innovación tecnológica y servicio a Nivel Nacional.</p>

                        </div>
                        <div class="span3">
                            <img src="/branding/images/nq-call-blocker-sug.png" alt="image01" style="width:65%">
                        </div>
                    </div>

                </div>
                <div class="row-fluid">
                    <div class="span4">
                        <div class="centered service">
                            <div class="circle-border zoom-in">
                                <img class="img-circle iconscustom" src="/branding/images/ops_img1.png" alt="service 1">
                            </div>
                            <h3>Seguro</h3>
                            <p>Vehículos registrados ante la SEMOVI y usuarios registrados en la base de datos de TACCSI.</p>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="centered service">
                            <div class="circle-border zoom-in">
                                <img class="img-circle iconscustom" src="/branding/images/ops_img2.png" alt="service 2" />
                            </div>
                            <h3>Tarifas justas </h3>
                            <p>Tarifas justas  (de  acuerdo  a la Entidad Federativa) .</p>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="centered service">
                            <div class="circle-border zoom-in">
                                <img class="img-circle iconscustom" src="/branding/images/ops_img3.png" alt="service 3">
                            </div>
                            <h3>Fácil</h3>
                            <p>Fácil de descargar y usar.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Service section end -->
        <!-- About us section end -->
        <div class="section secondary-section">
            <div class="triangle"></div>
            <div class="container centered">
                <p class="large-text">Tomar un taxi, nunca fue tan fácil. Proximamente busca nuestra aplicación en:</p>
                <a href="#" class="button">Apple Store</a>
                <a href="#" class="button">Google Play</a>
            </div>
        </div>
        <!-- Client section start -->
        <!-- Client section start -->
        <div id="clients">
            <div class="section primary-section">
                <div class="triangle"></div>
                <div class="container">
                    <div class="title">
                        <h1>Nuestros clientes</h1>
                        <p>Algunos de nuesros clientes satisfechos.</p>
                    </div>
                    <div class="row">
                        <div class="span4">
                            <div class="testimonial">
                                <p>"Gracias a TACCSI, puedo saber los ingresos que genera cada una de mis unidades. y poder mejorar el servicio que ofrece cada uno de mis operadores."</p>
                                <div class="whopic">
                                    <div class="arrow"></div>
                                    <!-- <img src="/branding/images/Client1.png" class="centered" alt="client 1">-->
                                    <strong>Alfredo Ramírez
                                        <small>Dueño de flota</small>
                                    </strong>
                                </div>
                            </div>
                        </div>
                        <div class="span4">
                            <div class="testimonial">
                                <p>"Desde que uso TACCSI, mis ingresos han aumentado. ya que puedo conseguir mas viajes utilizando la aplicación móvil."</p>
                                <div class="whopic">
                                    <div class="arrow"></div>
                                    <!-- <img src="/branding/images/Client2.png" class="centered" alt="client 2">-->
                                    <strong>Mario Hernández
                                        <small>Taxista independiente</small>
                                    </strong>
                                </div>
                            </div>
                        </div>
                        <div class="span4">
                            <div class="testimonial">
                                <p>"Había usado otras plataformas móviles de taxis. Pero, solo con TACCSI he exprimentado un servicio de calidad y oportuno."</p>
                                <div class="whopic">
                                    <div class="arrow"></div>
                                    <!--<img src="/branding/images/Client3.png" class="centered" alt="client 3">-->
                                    <strong>Angel Rivas
                                        <small>Usuario</small>
                                    </strong>
                                </div>
                            </div>
                        </div>
                    </div>
                    <p class="testimonial-text">
                        "La Tranquilidad de usar una plataforma que te brinda Atención, Confort, Comodidad, Seguridad en cada uno de tus viajes, utilizando herramientas Inovadoras."
                    </p>
                </div>
            </div>
        </div>       
        <!-- Newsletter section end -->
        <div id="custom" class="custom">
            <div class="section secondary-section">
                <div class="container">
                    <div class="title">
                        <h1>Taxistas</h1>
                        <p>Si te registras podrás recibir y atender viajes, los beneficios de ser taccista son: <br/></p>    
                        <div class="row-fluid">
                            <div class="span4">
                                <div class="centered service">
                                    <div class="circle-border zoom-in">
                                        <img class="img-circle iconscustom" src="/branding/images/serv_img1.png" alt="service 1">
                                    </div>
                                    <h3></h3>
                                    <p>Mejorar la calidad en el servicio por medio de retroalimentación.</p>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="centered service">
                                    <div class="circle-border zoom-in">
                                        <img class="img-circle iconscustom" src="/branding/images/serv_img2.png" alt="service 2" />
                                    </div>
                                    <h3></h3>
                                    <p>Transacciones seguras.</p>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="centered service">
                                    <div class="circle-border zoom-in">
                                        <img class="img-circle iconscustom" src="/branding/images/serv_img3.png" alt="service 3">
                                    </div>
                                    <h3></h3>
                                    <p>Herramienta de apoyo para ubicar rutas alternativas.</p>
                                </div>
                            </div>
                        </div> 
                        <div class="row-fluid">
                            <div class="span4">
                                <div class="centered service">
                                    <div class="circle-border zoom-in">
                                        <img class="img-circle iconscustom" src="/branding/images/serv_img4.png" alt="service 1">
                                    </div>
                                    <h3></h3>
                                    <p>Administración de horarios de acuerdo a las necesidades de operación.</p>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="centered service">
                                    <div class="circle-border zoom-in">
                                        <img class="img-circle iconscustom" src="/branding/images/serv_img5.png" alt="service 2" />
                                    </div>
                                    <h3></h3>
                                    <p>Apoyo para la recuperación del vehículo en caso de robo a través de las autoridades municipales, estatales y federales.</p>
                                </div>
                            </div>      
                            <div class="span4">
                                <div class="centered service">
                                    <div class="circle-border zoom-in">
                                        <img class="img-circle iconscustom" src="/branding/images/serv_img6.png" alt="service 2" />
                                    </div>
                                    <h3></h3>
                                    <p>Consigue un mayor número de clientes diariamente.</p>
                                </div>
                            </div>                                  
                        </div>    
                        <br/>                    
                        <p>Para hacerlo solo debes de ingresar al siguiente enlace:
                            <a class="buttonreg" href="/main/register/index">
                                <p class="info-mail">Registrarte aqui</p>
                            </a>
                        </p>                                               
                    </div>
                </div>
            </div>            
        </div>
        <!-- Contact section start -->
        <div id="contact" class="contact">
            <div class="section secondary-section">
                <div class="container">
                    <div class="title">
                        <h1>Contáctanos</h1>
                        <p>Si deseas ponerte en contacto con nosotros, no dudes en escribirnos. Será un placer estar en contacto contigo <br/><br/>ó llamanos:</p>
                        
                        <a class="" href="tel:018004448294">
                            <p class="info-mail">01800 444 82 94</p>
                        </a>                           
                        

                    </div>
                </div>
                <div class="map-wrapper">
                    <div class="map-canvas" id="map-canvas">Cargando mapa...</div>
                    <div class="container">
                        <div class="row-fluid">
                            <div class="span5 contact-form centered">
                                <h3>Escríbenos</h3>
                                <div id="successSend" class="alert alert-success invisible">
                                    <strong>Gracias!</strong>Tu mensaje ha sido recibido, pronto nos pondremos en contacto.</div>
                                <div id="errorSend" class="alert alert-error invisible">Intenta de nuevo.</div>
                                <form id="contact-form" action="/branding/php/mail.php">
                                    <div class="control-group">
                                        <div class="controls">
                                            <input class="span12" type="text" id="name" name="name" placeholder="* Nombre..." />
                                            <div class="error left-align" id="err-name">Por favor, escriba su nombre.</div>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <div class="controls">
                                            <input class="span12" type="email" name="email" id="email" placeholder="* Correo electrónico..." />
                                            <div class="error left-align" id="err-email">Escriba una dirección de correo válida.</div>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <div class="controls">
                                            <input class="span12" type="phone" name="phone" id="phone" placeholder="* Teléfono..." />
                                            <div class="error left-align" id="err-phone">Escriba un número telefónico.</div>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <div class="controls">
                                            <textarea class="span12" name="comment" id="comment" placeholder="* Comentario..."></textarea>
                                            <div class="error left-align" id="err-comment">Escriba su comentario.</div>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <div class="controls">
                                            <button id="send-mail" class="message-btn">Enviar</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="span9 center contact-info">
                        <p>Carlos Arellano 14, Ciudad Satélite, Naucalpan</p>
                        <!--<p class="info-mail">contacto@taccsi.com</p>-->
                        <a class="buttonreg" href="mailto:contacto@taccsi.com">
                            <p class="info-mail">contacto@taccsi.com</p>
                        </a>                                            
                        <p><a href="tel:01800 444 82 94" style="color:white;">01800 444 82 94</a></p>
                        <!--<p>01 55 5555555555</p>-->
                        <div class="title">
                            <h3>Síguenos en nuestras redes sociales</h3>
                        </div>
                    </div>
                    <div class="row-fluid centered">
                        <ul class="social">
                            <li>
                                <a href="https://www.facebook.com/TaccsiMx">
                                    <span class="icon-facebook-circled"></span>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/TaccsiMx">
                                    <span class="icon-twitter-circled"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <br/><br/>
                    <div style="text-align: center; width: 100%;font-size: 38.5px; /*text-transform: uppercase;*/">
                        <h3>BUEN VIAJE </h3>                       
                        <br/>
                        <img src="/branding/images/bye.png" alt="image01" style="width:50%">                             
                    </div>        
                </div>
            </div>
        </div>
        <!-- Contact section edn -->
        <!-- Footer section start -->
        <div class="footer">
            <p>TACCSI&copy; 2015 Todos los derechos reservados</p>
        </div>
        <!-- Footer section end -->
        <!-- ScrollUp button start -->
        <div class="scrollup">
            <a href="#">
                <i class="icon-up-open"></i>
            </a>
        </div>

        <div id="loginPanel" style="position: fixed; right: 6%;width: 300px; height: 170px; top: 10%; z-index: 2147483647;display:none;">
            <div style="padding:5px;">
                <div class="login-box-body box_body_login" style="padding:5px;">
                    <div id="div-msgError" class="alert alert-danger alert-dismissable" style="display:none;">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <div id="div-msg" ></div>
                    </div>      
                    <form  method="post" id="formLogin">
                        <div class="">
                            <div class="col-xs-12" style="padding-right: 15px;">
                                <input type="text" class="custom-form-control" id="txt-user"  name="userid"  placeholder="Usuario (E-mail)"/>
                                <label id="lbl_user"  class="control-label" for="txt-user"  style="display:none;color:red;"><i class="fa fa-times-circle-o"></i>Usuario requerido</label>
                                <input id="txt-pass"  type="password" name="password" class="custom-form-control" placeholder="Contraseña"/>
                                <label id="lbl_pass"  class="control-label" for="txt-pass" style="display:none;color:red;"><i class="fa fa-times-circle-o"></i>Contraseña requerida</label>
                            </div>                            
                        </div>    
                        <div class="p-10">
                            <div class="col-xs-12" style="padding-right: 15px;">
                                <input type="radio" checked name="group2" value="passenger"> Pasajero
                                &nbsp;
                                <input type="radio" name="group2" value="driver"> Conductor
                            </div>                            
                        </div>        
                      <div class="  p-10">
                        <div class="col-xs-12">
                          <button  onclick="validatelogin();"  type="button" class="btn-block btn-flat btn_yellow">Ingresar</button>
                        </div>
                      </div>
                    </form>
                  </div><!-- /.login-box-body -->                
            </div>
        </div>
        <!-- ScrollUp button end -->
        <!-- Include javascript -->
        <script src="/branding/js/jquery.js"></script>
        <script type="text/javascript" src="/branding/js/jquery.mixitup.js"></script>
        <script type="text/javascript" src="/branding/js/bootstrap.js"></script>
        <script type="text/javascript" src="/branding/js/modernizr.custom.js"></script>
        <script type="text/javascript" src="/branding/js/jquery.bxslider.js"></script>
        <script type="text/javascript" src="/branding/js/jquery.cslider.js"></script>
        <script type="text/javascript" src="/branding/js/jquery.placeholder.js"></script>
        <script type="text/javascript" src="/branding/js/jquery.inview.js"></script>
        <!-- Load google maps api and call initializeMap function defined in app.js -->
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&amp;callback=initializeMap"></script>
        <!-- css3-mediaqueries.js for IE8 or older -->
        <!--[if lt IE 9]>
            <script src="/branding/js/respond.min.js"></script>
        <![endif]-->
        <script src="/controllers/login/js/login.js" type="text/javascript"></script>    
        <script type="text/javascript" src="/branding/js/app.js"></script>
    </body>
</html>