<style type="text/css">
	.sl3-img{
		background-color: #FED600;
		background-image: url("/images/assets/background-slide.png");
		display: inline-block;
		font-weight: bold;
		height: 100%;
		margin-left: 15px;
		margin-right: 15px;
		position: relative;
		width: 100px;
		border-radius: 100px;
	}
	.div-text {
		font-size: 1.3em;
		font-weight: bold;
		margin-top: 35%;
		position: absolute;
		text-align: center;
		width: 100%;
	}
	.div-text-large{
		font-size: 1.3em;
		font-weight: bold;
		position: absolute;
		text-align: center;
		width: 100%;
		top: 10px;	
	}
	.item-info{
		height: 100px;
		margin-bottom: 5px;
		margin-left: 15%;
		width: 80%;
	}
	.inside-s3{
		background-color: #FFFFFF;
		border-radius: 10px;
		height: 90%;
		left: 5%;
		position: relative;
		top: 15px;
		width: 90%;		
	}
	.sl3-left{
		float: left;
		text-align: left;

	}
	.sl3-right{
		float: right;
	}
	.sl3-desc{
		position: relative;
		top: 40%;
		width: 70%;
	}
	.sl3-desc-2{
		position: relative;
		top: 0%;
		width: 70%;		
	}
</style>
<div class="slide" id="slide3" data-slide="3" data-stellar-background-ratio="0.5">
	<div class="inside-s3">

		<div class="item-info">
			<div class="sl3-img sl3-left">
				<div class="div-text">Movilidad</div>				
			</div>
			<div class="sl3-desc sl3-left">
				Solicite servicio de Taccsi desde su dispositivo móvil en donde quiera que se encuentre.
			</div>
		</div>

		
		<div class="item-info">
			<div class="sl3-desc sl3-left">
				Asignación efectiva de Taccsis, visualización del tacci en el mapa desde el momento de la asignación.
			</div>
			<div class="sl3-img sl3-left">
				<div class="div-text">Eficiencia</div>				
			</div>
		</div>

		<div class="item-info">
			<div class="sl3-img sl3-left">
				<div class="div-text-large">Seguridad y confiabilidad</div>				
			</div>
			<div class="sl3-desc-2 sl3-left">
				Grupo UDA como líder experto en seguridad de automóviles con rastreo satelital aunado al estricto control para el registro de conductores y automóviles que podrán pertenecer a la red de Taccsis le brindarán la confiabilidad de tener un traslado seguro.
			</div>
		</div>	

		<div class="item-info">
			<div class="sl3-desc sl3-left">
				Por medio de la App y página Web podrá solicitar el servicio el cual será atendido en el momento que lo necesita.
			</div>
			<div class="sl3-img sl3-left">
				<div class="div-text">Rapidez</div>				
			</div>
		</div>			
	</div>			
</div>