 <style type="text/css">
 .bloque-texto{
    left: 15%;
    position: relative;
 }
 .link-descarga{
    background-color: rgba(0, 0, 0, 0.4);
    border-radius: 15px;
    left: 60%;
    position: absolute;
    top: 55%;
    width: 450px;
    z-index: 1;
    height: 105px;
 }
 .link-imgs{
    float: left;
    width: 100%;
 }
 .link-img{
  float: left;
  margin-left: 15px;
 }
 .link-desc{
    color: #FFFFFF;
    font-size: 25px;
    font-weight: bold;
    text-align: center;  
 }
 </style>
 <div id="navigation">

  <div class="expand-down" align="left">
   <ul class="navigation">
   	<li data-slide="1">
      <a href="javascript:void(0);" >
      		<img src="/images/assets/bloque1.png"/><span>Inicio</span></a>   		
   	</li>   	
   	<br/>
    <li data-slide="2">
      <a href="javascript:void(0);" >
      		<img src="/images/assets/bloque2.png"/><span>por que usar</span></a>
    </li>
    <br/>
    <li data-slide="3">
      <a href="javascript:void(0);" >
      		<img src="/images/assets/bloque3.png"/><span>como funciona</span></a>
    </li>
    <br/>    
    <li data-slide="4">
      <a href="javascript:void(0);" >
      		<img src="/images/assets/bloque4.png"/><span>contacto</span></a>
    </li>    
    </ul>
</div>
</div>
<div class="slide" id="slide1" data-slide="1" data-stellar-background-ratio="0.5">

  <div id="img-logo">
    <img src="/images/assets/icon-page.png" />
  </div>

  <div class="link-descarga">
    <div class="link-desc">Descarga la aplicación</div>
    <div class="link-imgs">
      <div class="link-img">
        <img src="/images/assets/store-play.png" />
      </div>
      <div class="link-img">
        <img src="/images/assets/store-app.png" />
      </div>
    </div>
  </div>

	<div id="owl-demo" class="owl-carousel owl-theme">

    <div class="item">              
      <div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
            <img width="100%" height="600px" class="cycle" src="/images/slides/img-slide2.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
              Taccsi, el mejor servicio de Taccsi.<br/>
              Movilidad, eficiencia, seguridad, rapidez al alcance de un touch.
              </div>
            </div>            
      </div>
    </div>

    <div class="item">              
      <div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
            <img width="100%" height="600px" class="cycle" src="/images/slides/img-slide3.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
              Taccsi, el mejor servicio de Taccsi.<br/>
              Movilidad, eficiencia, seguridad, rapidez al alcance de un touch.
              </div>
            </div>            
      </div>
    </div>

    <div class="item">              
      <div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
            <img width="100%" height="600px" class="cycle" src="/images/slides/img-slide4.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
              Taccsi, el mejor servicio de Taccsi.<br/>
              Movilidad, eficiencia, seguridad, rapidez al alcance de un touch.
              </div>
            </div>            
      </div>
    </div>

    <div class="item">              
      <div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
            <img width="100%" height="600px" class="cycle" src="/images/slides/img-slide7.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
              Taccsi, el mejor servicio de Taccsi.<br/>
              Movilidad, eficiencia, seguridad, rapidez al alcance de un touch.
              </div>
            </div>            
      </div>
    </div>            

		<div class="item">							
			<div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
	        	<img width="100%" height="600px" class="cycle" src="/images/slides/img-slide8.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
              Taccsi, el mejor servicio de Taccsi.<br/>
              Movilidad, eficiencia, seguridad, rapidez al alcance de un touch.
              </div>
            </div>            
			</div>
		</div>	
		<div class="item">							
			<div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
	        	<img width="100%" height="600px" class="cycle" src="/images/slides/img-slide9.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
                Pide un Taccsi,<br/> obtén una gran experiencia de viaje por la ciudad sin estrés.
              </div>
            </div>                  
			</div>
		</div>	
			<div class="item">							
			<div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
	        	<img width="100%" height="600px" class="cycle" src="/images/slides/img-slide10.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
                La seguridad garantizada por Grupo UDA,<br/> el pionero en rastreo satelital con más de 15 años de experiencia.
              </div>
            </div>               
			</div>
		</div>		
          <div class="item">              
      <div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
            <img width="100%" height="600px" class="cycle" src="/images/slides/img-slide11.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
                La seguridad garantizada por Grupo UDA,<br/> el pionero en rastreo satelital con más de 15 años de experiencia.
              </div>
            </div>               
      </div>
    </div>  
    		      <div class="item">              
      <div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
            <img width="100%" height="600px" class="cycle" src="/images/slides/img-slide12.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
                La seguridad garantizada por Grupo UDA,<br/> el pionero en rastreo satelital con más de 15 años de experiencia.
              </div>
            </div>               
      </div>
    </div>  
      <div class="item">              
      <div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
            <img width="100%" height="600px" class="cycle" src="/images/slides/img-slide14.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
                La seguridad garantizada por Grupo UDA,<br/> el pionero en rastreo satelital con más de 15 años de experiencia.
              </div>
            </div>               
      </div>
    </div> 

      <div class="item">              
      <div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
            <img width="100%" height="600px" class="cycle" src="/images/slides/img-slide15.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
                La seguridad garantizada por Grupo UDA,<br/> el pionero en rastreo satelital con más de 15 años de experiencia.
              </div>
            </div>               
      </div>
    </div> 

      <div class="item">              
      <div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
            <img width="100%" height="600px" class="cycle" src="/images/slides/img-slide16.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
                La seguridad garantizada por Grupo UDA,<br/> el pionero en rastreo satelital con más de 15 años de experiencia.
              </div>
            </div>               
      </div>
    </div> 

      <div class="item">              
      <div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
            <img width="100%" height="600px" class="cycle" src="/images/slides/img-slide17.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
                La seguridad garantizada por Grupo UDA,<br/> el pionero en rastreo satelital con más de 15 años de experiencia.
              </div>
            </div>               
      </div>
    </div> 

      <div class="item">              
      <div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
            <img width="100%" height="600px" class="cycle" src="/images/slides/img-slide18.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
                La seguridad garantizada por Grupo UDA,<br/> el pionero en rastreo satelital con más de 15 años de experiencia.
              </div>
            </div>               
      </div>
    </div> 
      <div class="item">              
      <div id="" style="background-color: #FFFFFF;height: 60%;width: 100%;margin-left: 0%;">
            <img width="100%" height="600px" class="cycle" src="/images/slides/img-slide19.jpg">
            <div class="bloque-description">
              <div class="bloque-texto">
                La seguridad garantizada por Grupo UDA,<br/> el pionero en rastreo satelital con más de 15 años de experiencia.
              </div>
            </div>               
      </div>
    </div>                              
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
 
  var owl = $("#owl-demo");
 
  owl.owlCarousel({
      items : 1, //10 items above 1000px browser width
      itemsDesktop : [1000,1], //5 items between 1000px and 901px
      itemsDesktopSmall : [1000,1], // betweem 900px and 601px
      itemsTablet: [1000,1], //2 items between 600 and 0
      itemsMobile : false // itemsMobile disabled - inherit from itemsTablet option
  });
  //owl.trigger('owl.play',9000); //owl.play event accept autoPlay speed as second parameter

});
</script>