<?php $this->headScript()->appendFile('/controllers/main/validateRegister.js') ?>
<aside class="right-side">
    <section class="content">
        <div class="col-xs-9">            
          <div class="box box-primary row-min-h600">
                <div class="box-header">
                    <div class="col-md-8">
                        <h3 class="box-title">Registro de Taccista</h3>
                    </div>
                    <div class="col-md-4">
                        <div class="header">
                            <img src="/images/assets/icon-page.png" class="img-responsive center-block" alt="Logo">
                        </div>                     
                    </div>                
                </div>  

                <?php if(count(@$this->errors)>0):?>
                    <?php if(@$this->errors['eUsuario']==1):?>
                        <div id="divAlert" class="alert alert-danger alert-dismissable">
                            <i class="fa fa-ban"></i>
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <b>!Atención Error¡</b>
                            <div>                
                                El usuario ya se encuentra registrado, favor de verificarlo.
                            </div>
                        </div>  
                    <?php elseif(@$this->errors['status']==1):?>
                        <div id="divAlert" class="alert alert-danger alert-dismissable">
                            <i class="fa fa-ban"></i>
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <b>!Atención Error¡</b>
                            <div>                
                                Ocurrio un error en el registro, favor de intentarlo mas tarde.
                            </div>
                        </div>          
                    <?php endif;?>    
                <?php endif; ?>

                <?php if(@$this->resultOp=='okRegisterMail'):?>
                    <div class="alert alert-success alert-dismissable">
                        <i class="fa fa-check"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <b>!Atención¡</b>Sus datos se han registrado correctamente.<br/>
                        En breve uno de nuestros ejecutivos se pondra en contacto con usted para continuar con el proceso de registro.
                    </div>
                <?php elseif(@$this->resultOp=='okRegister'):?>
                    <div class="alert alert-success alert-dismissable">
                        <i class="fa fa-check"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <b>!Atención¡</b>Sus datos se han registrado correctamente.<br/>
                        En este momento ya puede hacer uso de la aplicación, para poder utilizarla es necesario descargarla, a contiuación los enlaces: 
                        <table class="col-md-12">
                            <tr>
                                <td>
                                    <a target="_blank" href="http://store.apple.com/mx">
                                        <img src="/images/assets/esAppStore.png" style="width:100px;"/>
                                    </a>
                                </td>
                                <td style="width:50px;"></td>
                                <td>
                                    <a target="_blank" href="https://play.google.com/">
                                        <img src="/images/assets/esGooglePlay.png" style="width:100px;"/>
                                    </a>
                                </td>
                            </tr>
                        </table>
                    </div>
                <?php else:?>                
                    <form role="form" method="POST" action="/main/register/index" id="FormData" enctype="multipart/form-data">
                        <input type="hidden" name="optReg" value="opRegister" />
                        <div class="box-body">
                              <div class="col-xs-12">
                                    <div class="form-group col-xs-4">
                                        <label for="inputNombre">Nombre</label>
                                        <input type="text" class="form-control upperClass"  autocomplete="off"  name="inputNombre" id="inputNombre" placeholder="Nombre(s)" value="<?php echo @$this->data['inputNombre']; ?>">
                                    </div>
                                    <div class="form-group col-xs-4">
                                        <label for="inputApaterno">Ap. Paterno</label>
                                        <input type="text" class="form-control upperClass" autocomplete="off"  name="inputApaterno" id="inputApaterno" placeholder="Apellido Paterno" value="<?php echo @$this->data['inputApaterno']; ?>">
                                    </div>
                                    <div class="form-group col-xs-4">
                                        <label for="inputAmaterno">Ap. Materno</label>
                                        <input type="text" class="form-control upperClass" autocomplete="off"  name="inputAmaterno" id="inputAmaterno" placeholder="Apellido Materno" value="<?php echo @$this->data['inputAmaterno']; ?>">
                                    </div>
                                </div>

                                <div class="col-xs-12">
                                    <div class="form-group col-xs-4">
                                        <label for="inputNombre">Usuario (E-mail)</label>
                                        <input type="text" class="form-control" autocomplete="off"  name="inputUsuario" id="inputUsuario" placeholder="Usuario" value="<?php echo @$this->data['inputUsuario']; ?>">
                                    </div>
                                    <div class="form-group col-xs-4">
                                        <label for="inputApaterno">Contraseña</label>
                                        <input type="password" class="form-control" name="inputPassword" id="inputPassword" placeholder="******" onChange="addValidatePass(this.value)">
                                    </div>
                                    <div class="form-group col-xs-4">
                                        <label for="inputAmaterno">Confirmar Contraseña</label>
                                        <input type="password" class="form-control " name="inputCpassword" id="inputCpassword" placeholder="******">
                                    </div>
                                </div>                        
                               <div class="col-xs-12">                 
                                    <div class="form-group col-xs-4">
                                        <label for="inputPhone">Teléfono</label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-phone"></i>
                                            </div>                            
                                            <input type="text" class="form-control upperClass col-xs-4" autocomplete="off"  name="inputPhone" id="inputPhone" placeholder="Teléfono" value="<?php echo @$this->data['inputPhone']; ?>">
                                        </div>
                                    </div>                            
                                    <div class="form-group col-xs-4">
                                        <label for="inputTaxip">¿Taxi Propio?</label>
                                        <div class="input-group col-xs-12">                     
                                            <select class="form-control" id="inputTaxip" name="inputTaxip" >
                                                <option value="">Seleccione una opción</option>
                                                <?php echo $this->taxpropio;?>                                
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group col-xs-4">
                                        <label for="inputAmaterno">Clave Empresa</label>
                                        <input type="text" class="form-control" autocomplete="off"  name="inputCodEmp" id="inputCodEmp" placeholder="Clave Empresa" value="<?php echo @$this->data['inputCodEmp']; ?>">
                                    </div>
                                </div>
                            <h4>Información del Taxi</h4>
                            <div class="col-xs-12">
                                <div class="form-group col-xs-6">
                                    <label for="inputNombre">Marca</label>
                                    <div class="input-group col-xs-12">                     
                                        <select class="form-control upperClass" id="inputMarca" autocomplete="off"  name="inputMarca" onChange="getoptionsCbo('Modelo','modeloe',this.value,'','');">
                                            <option value="">Seleccione una opción</option>
                                            <?php echo $this->aMarcas;?>                                
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-xs-6">
                                    <label for="inputApaterno">Modelo</label>
                                    <div class="input-group col-xs-12">      
                                        <div id="divModelo">
                                            <select class="form-control upperClass" name="inputModelo" id="inputModelo" >
                                                <option value="">Seleccionar una opción</option>
                                                <?php echo $this->aModelos;  ?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="form-group col-xs-6">
                                    <label for="inputAmaterno">Color</label>
                                    <div class="input-group col-xs-12">                     
                                        <select class="form-control upperClass" id="inputColor" name="inputColor" >
                                            <option value="">Seleccione una opción</option>
                                            <?php echo $this->aColores;?>                                
                                        </select>
                                    </div>
                                </div>           

                                <div class="form-group col-xs-6">
                                    <label for="inputNombre">Año</label>
                                    <input type="text" class="form-control upperClass" name="inputAno" autocomplete="off"  id="inputAno" placeholder="Año" value="<?php echo @$this->data['inputAno']; ?>">
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="form-group col-xs-6">
                                    <label for="inputNombre">Placas</label>
                                    <input type="text" class="form-control upperClass" name="inputPlacas" autocomplete="off"  id="inputPlacas" placeholder="Placas" value="<?php echo @$this->data['inputPlacas']; ?>">
                                </div>                                        
                                <div class="form-group col-xs-6">
                                    <label for="inputApaterno">Eco</label>
                                    <input type="text" class="form-control upperClass" name="inputEco" autocomplete="off"  id="inputEco" placeholder="ECO" value="<?php echo @$this->data['inputEco']; ?>">
                                </div>
                            </div>                                      
                        </div>

                        <div class="box-footer col-xs-12">                                                        
                            <button type="submit" class="btn btn-primary pull-right margin-5">Enviar Información</button>
                        </div>
                    </form>   
                <?php endif;?> 
            </div><!-- /.box -->
        </div>
    </section><!-- /.content -->