
<aside class="right-side">
    <section class="content">
        <div id="divAlert" class="alert alert-danger alert-dismissable hide">
            <i class="fa fa-ban"></i>
            <b>!Atención¡</b>
            <div id="divErrorContent">                
            </div>
        </div>

        <div class="col-xs-9">
          <div class="box box-primary row-min-h450">
                <div class="box-header">
                    <h3 class="box-title">Registro de Sitios de Taxis</h3>
                </div>
            <form role="form" method="POST" action="/admin/cars/getinfo" id="FormData" enctype="multipart/form-data">
                <input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
                <input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />
  
                <?php if(count(@$this->errors)>0):?>
                 <div class="alert alert-danger alert-dismissable">
                        <i class="fa fa-ban"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <b>!Atención¡</b>
                        <?php if(@$this->errors['errorImage']==1):?>
                            <div>La imagen no fue posible guardarla, favor de verificar las especificaciones.</div>
                        <?php endif; ?>                                
                    </div>
                <?php endif;?>


                <div class="box-body">
                      <div class="col-xs-12">
                            <div class="form-group col-xs-4">
                                <label for="inputNombre">Nombre</label>
                                <input type="text" class="form-control upperClass" name="inputNombre" id="inputNombre" placeholder="Nombre(s)" value="<?php echo @$this->data['NOMBRE']; ?>">
                            </div>
                            <div class="form-group col-xs-4">
                                <label for="inputApaterno">Ap. Paterno</label>
                                <input type="text" class="form-control upperClass" name="inputApaterno" id="inputApaterno" placeholder="Apellido Paterno" value="<?php echo @$this->data['APATERNO']; ?>">
                            </div>
                            <div class="form-group col-xs-4">
                                <label for="inputAmaterno">Ap. Materno</label>
                                <input type="text" class="form-control upperClass" name="inputAmaterno" id="inputAmaterno" placeholder="Apellido Materno" value="<?php echo @$this->data['AMATERNO']; ?>">
                            </div>
                        </div>

                        <div class="col-xs-12">
                            <div class="form-group col-xs-4">
                                <label for="inputNombre">Usuario (E-mail)</label>
                                <input type="text" class="form-control upperClass" name="inputUsuario" id="inputUsuario" placeholder="Usuario" value="<?php echo @$this->data['NICKNAME']; ?>">
                            </div>
                            <div class="form-group col-xs-4">
                                <label for="inputApaterno">Contraseña</label>
                                <input type="password" class="form-control upperClass" name="inputPassword" id="inputPassword" placeholder="" onChange="addValidatePass(this.value)">
                            </div>
                            <div class="form-group col-xs-4">
                                <label for="inputAmaterno">Confirmar Contraseña</label>
                                <input type="password" class="form-control upperClass" name="inputCpassword" id="inputCpassword" placeholder="">
                            </div>
                        </div>                        
                       <div class="col-xs-12">                 
                            <div class="form-group col-xs-4">
                                <label for="inputPhone">Teléfono</label>
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-phone"></i>
                                    </div>                            
                                    <input type="text" class="form-control upperClass col-xs-4" name="inputPhone" id="inputPhone" placeholder="Teléfono" value="<?php echo @$this->data['TELEFONO']; ?>">
                                </div>
                            </div>
                            <div class="form-group col-xs-4">
                                <label for="inputPhone">Estatus</label>
                                <div class="input-group col-xs-12">                     
                                    <select class="form-control" id="inputEstatus" name="inputEstatus" >
                                        <option value="">Seleccione una opción</option>
                                        <?php echo $this->aStatus;?>                                
                                    </select>
                                </div>
                            </div>
                        </div>
                    <h4>Cuento con Taxi Propio</h4>
                    <div class="col-xs-12">
                        <div class="form-group col-xs-6">
                            <label for="inputNombre">Marca</label>
                            <div class="input-group col-xs-12">                     
                                <select class="form-control upperClass" id="inputMarca" name="inputMarca" onChange="getoptionsCbo('Modelo','modeloe',this.value,'','');">
                                    <option value="">Seleccione una opción</option>
                                    <?php echo $this->aMarcas;?>                                
                                </select>
                            </div>
                        </div>
                        <div class="form-group col-xs-6">
                            <label for="inputApaterno">Modelo</label>
                            <div class="input-group col-xs-12">      
                                <div id="divModelo">
                                    <select class="form-control upperClass" name="inputModelo" id="inputModelo" <?php echo $disabled;?> >
                                        <option value="">Seleccionar una opción</option>
                                        <?php echo $this->aModelos;  ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group col-xs-6">
                            <label for="inputAmaterno">Color</label>
                            <div class="input-group col-xs-12">                     
                                <select class="form-control upperClass" id="inputColor" name="inputColor" >
                                    <option value="">Seleccione una opción</option>
                                    <?php echo $this->aColores;?>                                
                                </select>
                            </div>
                        </div>           

                        <div class="form-group col-xs-6">
                            <label for="inputNombre">Año</label>
                            <input type="text" class="form-control upperClass" name="inputAno" id="inputAno" placeholder="Año" value="<?php echo @$this->data['ANIO']; ?>">
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group col-xs-6">
                            <label for="inputNombre">Placas</label>
                            <input type="text" class="form-control upperClass" name="inputPlacas" id="inputPlacas" placeholder="Placas" value="<?php echo @$this->data['PLACAS']; ?>">
                        </div>                                        
                        <div class="form-group col-xs-6">
                            <label for="inputApaterno">Eco</label>
                            <input type="text" class="form-control upperClass" name="inputEco" id="inputEco" placeholder="ECO" value="<?php echo @$this->data['ECO']; ?>">
                        </div>
                    </div>
                    <!--
                    <div class="col-xs-12">
                        <div class="form-group col-xs-6">
                            <label for="inputAmaterno">Nombre Chofer</label>
                            <input type="text" class="form-control upperClass" name="inputChofer" id="inputChofer" placeholder="Nombre del Chofer" value="<?php echo @$this->data['NOMBRE_CHOFER']; ?>">
                        </div>                                            
                        <div class="form-group col-xs-6">
                            <label for="inputPhone">Estatus</label>
                            <div class="input-group col-xs-12">                     
                                <select class="form-control" id="inputEstatus" name="inputEstatus" >
                                    <option value="">Seleccione una opción</option>
                                    <?php echo $this->aStatus;?>                                
                                </select>
                            </div>
                        </div>
                    </div>  -->                                        
                </div><!-- /.box-body -->

                <div class="box-footer col-xs-12">                                                        
                    <button type="button" class="btn pull-right margin-5" onClick="javascript:backToMain()">Cancelar</button>
                    <button type="submit" class="btn btn-primary pull-right margin-5">Guardar</button>
                </div>
            </form>    
            </div><!-- /.box -->
        </div>
    </section><!-- /.content -->