<?php $this->headScript()->appendFile('/controllers/callcenter/services/js/scripts.js') ?>
    <section class="content">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Clientes con el mismo número</h3>
                </div>
                <div class="box-body table-responsive">                                    
                    <table id="tableCLients" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Ap. Paterno</th>
                                <th>Ap. Materno</th>
                                <th>Telèfono</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody> 
                            <?php foreach(@$this->aDataTable as $key => $items): ?>                              
                                <tr>
                                    <td><?php echo $items['NAME'];?></td>
                                    <td><?php echo $items['APP'];?></td>
                                    <td><?php echo $items['APM'];?></td>
                                    <td><?php echo $items['TELEFONO'];?></td>
                                    <td><button type="button" class="btn btn-primary" onClick="getToServicio(<?php echo $items['ID_SRV_USUARIO'];?>)"> 
                                        <i class="fa fa-arrow-circle-right"></i> </button></td>
                                </tr>                                
                            <?php endforeach;?>
                        </tbody>

                        <tfoot></tfoot>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </section><!-- /.content -->

<!-- COMPOSE MESSAGE MODAL -->
<div class="modal fade" id="ModalConfirm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Usuario no Existe</h4>
            </div>
                <div class="modal-body">
                    <div class="col-xs-offset-2" style="height: 50px;">
                        <button onClick="goToSetClient();" type="button" class="btn margin btn-success pull-left" data-dismiss="modal">Registrar Nuevo Cliente</button>
                        <button class="btn btn-primary margin pull-left" data-dismiss="modal">Buscar Otro Cliente</button>
                    </div>
                </div>
                <div class="modal-footer clearfix">                     
                    <!--<button type="button" class="btn btn-primary pull-left" data-dismiss="modal">Buscar Otro Cliente</button>-->
                </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->