<?php $this->headScript()->appendFile('/controllers/admin/js/jsValidateRegions.js') ?>
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>

<?php $this->headScript()->captureStart() ?>
  geos_poins_polygon = [ <?php echo @$this->aPositions;?> ];

  geos_options = {
          paths: geos_poins_polygon,
          editable: true,
          strokeColor: "#FF0000",
          strokeOpacity: 0.8,
          strokeWeight: 3,
          fillColor: "#FF0000",
          fillOpacity: 0.35
    }
<?php $this->headScript()->captureEnd(); ?>

<input id="hRefLinkMain" type="hidden" value="/finances/regions/index" />
<section class="content">
    <div class="col-xs-12">
        <div class="box box-primary row-min-h800">
            <div class="box-header">
                <h3 class="box-title">Información de la Región</h3>
            </div>
            <div class="box-body">
                <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
                    <li class="<?php echo (!isset($this->sOperation) || @$this->resultOp=='okRegister') ? 'active': ''; ?>"><a href="#table" data-toggle="tab" aria-expanded="true">Información General</a></li>
                    <li class="<?php echo (isset($this->sOperation) && @$this->resultOp=='okRegisterTarifas') ? 'active': ''; ?>"><a href="#tarifas" data-toggle="tab" aria-expanded="true">Tárifas</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane <?php echo (!isset($this->sOperation) || @$this->resultOp=='okRegister') ? 'active': ''; ?>" id="table">

                    <?php if(@$this->errors['status']):?>
                        <div id="divpErrorLogin" class="alert alert-error" style="display:block;">
                          <button type="button" class="close" data-dismiss="alert">×</button>
                          <h4>Error</h4>
                          <div>La Usuario no se encuentra disponible</div>
                        </div>
                    <?php endif;?>

                    <?php if(@$this->resultOp=='okRegister'):?>
                        <div class="alert alert-success alert-dismissable">
                            <i class="fa fa-check"></i>
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <b>!Atención¡</b> Los datos se han guardado correctamente.
                        </div>
                    <?php endif;?>

                    <?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
                        <div id="divAlert" class="alert alert-danger alert-dismissable">
                            <i class="fa fa-ban"></i>
                            <b>!Atención¡</b>
                            <div>Usted no tiene permiso para ver esta información</div>
                        </div>                                      
                    <?php else:?>   
                    <form role="form" method="POST" action="/finances/regions/getinfo?catId=<?php echo $this->catId; ?>" id="FormData" >
                        <input type="hidden" id="optReg" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
                        <input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />
                        <textarea style="display:none;" id="inputPoints"     name="inputPoints"  ></textarea>                        
                        <div class="box-body">
                           <div class="col-xs-12">
                                <div class="form-group col-xs-4">
                                    <label for="inputNombre">Descripción</label>
                                    <input type="text" class="form-control upperClass" autocomplete="off" name="inputNombre" id="inputNombre" placeholder="Descripción" value="<?php echo @$this->data['DESCRIPCION']; ?>">
                                </div>
                                <div class="form-group col-xs-4">
                                    <label for="input">Estatus</label>
                                    <div class="input-group col-xs-12">                     
                                        <select class="form-control" id="inputEstatus" name="inputEstatus" >
                                            <option value="">Seleccione una opción</option>
                                            <?php echo $this->aStatus;?>                                
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-xs-4">
                                    <label for="inputEstado">La región Abarca:</label>
                                    <div class="input-group col-xs-12">                     
                                        <select class="form-control" id="inputEstado" name="inputEstado"  onChange="selectEstado(this.value)">
                                            <option value="">Seleccione una opción</option>
                                            <option value="-1">Zona Especifica</option>
                                            <?php echo $this->aEstados;?>                                
                                        </select>
                                    </div>
                                </div>                                
                            </div> 

                            <div class="col-xs-12" id="divSearch" style="display:none;">
                                <div class="col-xs-6">
                                    <label for="inputEstado">Buscar Region,Municipio, Colonia,etc..</label>
                                    <div class="input-group col-xs-12">                     
                                        <input type="text" class="form-control noEnterSubmit nopaste" name="inputOrigen" id="inputOrigen" placeholder="Colonia, Delefación o Municipio" value="">
                                    </div>
                                    <br/>
                                </div>
                                <div class="col-xs-6">
                                   
                                </div>
                            </div>                            
                            <br/>
                            <br/>
                            <div id="myMapDraw" style="width:100%; height:350px;"></div>

                            <br/>

                            <div class="form-group">
                              
                            </div>
                          </div>

                          <div class="box-footer">
                            <div class="pull-right">
                                <button type="button" class="btn margin-5" onClick="javascript:backToMain()">Cancelar</button>
                                <button type="submit" class="btn btn-primary margin-5">Guardar</button>
                            </div>
                          </div>
                        </form>  
                    <?php endif;?>
                    </div>
                    <div class="tab-pane <?php echo (isset($this->sOperation) && @$this->resultOp=='okRegisterTarifas') ? 'active': ''; ?>" id="tarifas" style="display:<?php echo (@$this->catId==-1) ? 'none':'block';?>">
                        <div class="pull-right p-10">
                            <a href="/finances/regions/getinfo?catId=-1"><button class="btn btn-success"><i class="fa fa-plus"></i> Agregar</button></a>            
                        </div>                                  
                        <table id="dataTableTar" class="table table-bordered table-striped">
                            <thead>
                                <tr>               
                                    <th>Descripción</th>
                                    <th>Tipo Taxi</th>
                                    <th>Banderazo</th>
                                    <th>Costo Km Recorrido</th>
                                    <th>Costo Km Fuera de Zona</th>
                                    <th>Costo H. Nocturno</th>
                                    <th>Estatus</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($this->aTarifas as $key => $items): ?>  
                                <tr class="odd gradeX">   
                                    <td><?php echo $items['DESCRIPCION']; ?></td>                   
                                    <td><?php echo $items['N_CLASE']; ?></td>                   
                                    <td><?php echo "$ ".number_format($items['COSTO_BANDERAZO']); ?></td>
                                    <td><?php echo "$ ".number_format($items['DISTANCIA_POR_COBRAR']); ?></td>
                                    <td><?php echo "$ ".number_format($items['COSTO_FUERA_ZONA']); ?></td>
                                    <td><?php echo "$ ".number_format($items['COSTO_EXTRA_NOCHE']); ?></td>
                                    <td><?php echo $items['N_ESTATUS']; ?></td>
                                    <!--
                                    <td><?php echo $items['DESCRIPCION']; ?></td>                   
                                    <td><?php echo $items['ESTADO']; ?></td>
                                    <td><?php echo $items['ESTATUS']; ?></td>-->
                                    <td class="text-center" style="width:100px;">
                                        <?php if($this->dataUser['LECTURA']==1): ?>
                                            <a href="/finances/regions/getinfo?catId=<?php echo $items['ID']; ?>"><button class="btn btn-primary"> <i class="fa fa-eye"></i></button></a>   
                                        <?php endif;?> 
                                    </td>
                                </tr>    
                                <?php endforeach;?>                        
                            </tbody>
                        </table>                        
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>