<?php $this->headScript()->appendFile('/controllers/gralTables.js') ?>
<?php $this->headScript()->appendFile('/controllers/admin/js/tableUsers.js') ?>
<input id="hRefLinkEdit" type="hidden" value="/admin/drivers/getinfo?idRow=" />

	<section class="content">
        <div class="box">
            <div class="box-header">                 
                <h3 class="box-title">Taxis sin Verificar</h3>
                <div class="pull-right p-10">
                </div>                                  
            </div><!-- /.box-header -->
            <div class="box-body table-responsive">
                <table id="dataTable" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Empresa</th>                                           
                            <th>Placas</th>
                            <th>ECO</th>
                            <th>Documentos</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->datatTable as $key => $items): ?>  
                        <tr class="odd gradeX">                     
                            <td><?php echo $items['NOMBRE_EMPRESA']; ?></td>
                            <td><?php echo $items['PLACAS']; ?></td>
                            <td><?php echo $items['ECO']; ?></td>
                            <td><?php echo $items['N_DOCS']; ?></td>
                            <td class="text-center">
                                <?php if($this->dataUser['LECTURA']==1): ?>
                                    <a href="/admin/valtaxis/getinfo?catId=<?php echo $items['ID_TAXI']; ?>"><button class="btn btn-primary"> <i class="fa fa-eye"></i></button></a>   
                                <?php endif;?> 
                                <!--
                                <?php if($this->dataUser['ELIMINAR']==1): ?>
                                    <a href="javascript:confirmDelete('<?php echo $items['ID_USUARIO']; ?>')"><button class="btn btn-danger"> <i class="fa fa-trash-o"></i></button></a>
                                <?php endif;?>-->
                            </td>
                        </tr>    
                        <?php endforeach;?>                        
                    </tbody>
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->       
    </section><!-- /.content -->