<?php $this->headScript()->appendFile('/controllers/callcenter/atn/js/scripts.js') ?>
<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header no-margin">
        <h1 class="text-center">
            <a class="pull-left" href="/callcenter/main/index">
                <i class="fa fa-arrow-circle-left"></i>
            </a>            
            <?php echo $this->dataClient['NOMBRE']." ".$this->dataClient['APATERNO']." ".$this->dataClient['AMATERNO']; ?>
            <div class="btn-group pull-right">
                <button type="button" onclick="javascript:location.href='/callcenter/services/createservice?strClient=<?php echo $this->dataClient['ID_CLIENTE']; ?>'" class="btn btn-success btn-flat"><i class="fa  fa-plus"></i> Nuevo Viaje</button>
            </div>  
        </h1>
    </section>
    <section class="content">
        <!-- MAILBOX BEGIN -->
        <div class="mailbox row">
            <div class="col-xs-12">
                <div class="box box-solid">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-3 col-sm-4">
                                <div class="box-header">
                                    <i class="fa fa-info-circle"></i>
                                    <h3 class="box-title">Datos del Cliente</h3>
                                </div>
                                <div style="margin-top: 15px;">
                                    <ul class="nav nav-pills nav-stacked">
                                        <li>Total Viajes:</li>
                                        <li class="header"><?php echo ($this->dataClient['VIAJES']!="") ? $this->dataClient['VIAJES'] : '---'; ?></li>
                                        <li>Nombre Completo:</li>
                                        <li class="header"><?php echo $this->dataClient['NOMBRE']." ".$this->dataClient['APATERNO']." ".$this->dataClient['AMATERNO']; ?></li>
                                        <li>Teléfono:</li>
                                        <li class="header"><?php echo $this->dataClient['TELEFONO']; ?></li>
                                        <li>Usuario:</li>
                                        <li class="header"><?php echo ($this->dataClient['USUARIO']!="") ? $this->dataClient['USUARIO'] : '---'; ?></li>
                                        <li>E-Mail:</li>
                                        <li class="header"><?php echo ($this->dataClient['EMAIL']!="") ? $this->dataClient['EMAIL'] : '---'; ?></li>                                        
                                        <li>Fecha de Registro:</li>
                                        <li class="header"><?php echo $this->dataClient['FECHA_CREACION']; ?></li>
                                    </ul>
                                </div>
                            </div><!-- /.col (LEFT) -->
                            <div class="col-md-9 col-sm-8">

                                        <div class="box-body table-responsive">                                    
                                            <table id="tableViajes" class="table table-bordered table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>Id Viaje</th>
                                                        <th>Fecha</th>
                                                        <th>Taxista</th>
                                                        <th>Taxi</th>
                                                        <th>Estatus</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php foreach($this->dataViajes as $key => $items):?>
                                                        <tr>
                                                            <td><?php echo $items['ID_VIAJES']; ?></td>
                                                            <td><?php echo $items['FECHA_VIAJE']; ?></td>
                                                            <td><?php echo $items['TAXISTA']; ?></td>
                                                            <td><?php echo $items['PLACAS']; ?></td>
                                                            <td><?php echo $items['ESTATUS']; ?></td>
                                                            <td><button type="button" class="btn btn-primary" onClick="getToServicio('<?php echo $items['ID_VIAJES']; ?>')">
                                                                <i class="fa fa-arrow-circle-right"></i> </button></td>
                                                        </tr>
                                                    <?php endforeach;?>
                                                </tbody>
                                                <tfoot></tfoot>
                                            </table>
                                        </div><!-- /.box-body -->
 
                                </div><!-- /.tab-content -->
                            </div>

                            </div><!-- /.col (RIGHT) -->
                        </div><!-- /.row -->
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
    </section><!-- /.content -->
</aside><!-- /.right-side -->