<?php $this->headScript()->appendFile('/controllers/callcenter/services/js/validateClient.js') ?> 
<aside class="right-side">
	<section class="content">
        <div id="divAlert" class="alert alert-danger alert-dismissable hide">
            <i class="fa fa-ban"></i>
            <b>!Atención¡</b>
            <div id="divErrorContent">                
            </div>
        </div>

    	<div class="col-xs-12">
          <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Nuevo Cliente</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
            	<?php if(@$this->errors['status']=='no-insert'):?>
			        <div id="divAlert" class="alert alert-danger alert-dismissable hide">
			            <i class="fa fa-ban"></i>
			            <b>!Error</b>
			            <div id="divErrorContent">    
			            	Ocurrio un error al insertar el cliente.
			            </div>
			        </div>					
				<?php elseif(@$this->errors['status']=='user-exist'):?>
			        <div id="divAlert" class="alert alert-danger alert-dismissable hide">
			            <i class="fa fa-ban"></i>
			            <b>!Error</b>
			            <div id="divErrorContent">    
			            	Ocurrio un error al insertar el cliente.
			            </div>
			        </div>					
				<?php endif;?>                
				<form role="form" method="POST" action="/callcenter/client/new" id="FormData" >
                	<input type="hidden" id="inputOpr"   name="optReg" value="new" />
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputNombre">Nombre</label>
                            <input type="text" class="form-control upperClass" name="inputNombre" id="inputNombre" placeholder="Nombre(s)">
                        </div>
                        <div class="form-group">
                            <label for="inputApaterno">Ap. Paterno</label>
                            <input type="text" class="form-control upperClass" name="inputApaterno" id="inputApaterno" placeholder="Apellido Paterno">
                        </div>
                        <div class="form-group">
                            <label for="inputAmaterno">Ap. Materno</label>
                            <input type="text" class="form-control upperClass" name="inputAmaterno" id="inputAmaterno" placeholder="Apellido Materno">
                        </div>
                        <div class="form-group">
                            <label for="inputPhone">Teléfono</label>
                            <div class="input-group">
								<div class="input-group-addon">
                                    <i class="fa fa-phone"></i>
                                </div>                            
                            	<input type="text" class="form-control upperClass" name="inputPhone" id="inputPhone" placeholder="Teléfono">
                            </div>
                        </div>           
                        <div class="form-group">
                            <label for="inputPhone">E-mail</label>
                            <div class="input-group">
								<div class="input-group-addon">
                                    <i class="fa fa-envelope"></i>
                                </div>                            
                            	<input type="text" class="form-control" name="inputEmail" id="inputEmail" placeholder="midireccion@dominio.com">
                            </div>
                        </div>    
                    </div><!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </form>
            </div><!-- /.box -->
        </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->		    