<?php $this->headScript()->appendFile('/controllers/admin/js/validateAssign.js') ?>
<input id="hRefLinkMain" type="hidden" value="/admin/validation/index" />

    <section class="content">
        <div class="col-xs-12">
          <div class="box box-primary row-min-h600">
                <div class="box-header">
                    <h3 class="box-title">Información del  Chofer</h3>
                </div>
                    <?php if(@$this->errors['update']==1):?>
                        <div id="divAlert" class="alert alert-danger alert-dismissable">
                            <i class="fa fa-ban"></i>
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <b>!Atención Error¡</b>
                            <div>                
                                Ocurrio un error al actualizar la información.
                            </div>
                        </div>                      
                    <?php endif;?>                  
                    <?php if(@$this->resultOp=='okRegister'):?>
                        <div class="alert alert-success alert-dismissable">
                            <i class="fa fa-check"></i>
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <b>!Atención¡</b>Sus datos se han registrado correctamente.<br/>                           
                        </div>
                    <?php endif;?> 

                    <form role="form" method="POST" action="/admin/validation/getinfo" id="FormData" enctype="multipart/form-data">
                        <input type="hidden" name="optReg"                      value="opRegister" />
                        <input type="hidden" name="iRespuesta" id="iRespuesta"  value="1" />
                        <input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />
                        <div class="box-body">
                              <div class="col-xs-12">
                                    <div class="form-group col-xs-4">
                                        <label for="inputNombre">Nombre</label>
                                        <input type="text" class="form-control upperClass"  autocomplete="off"  name="inputNombre" id="inputNombre" placeholder="Nombre(s)" value="<?php echo @$this->data['NOMBRE']; ?>" disabled >
                                    </div>
                                    <div class="form-group col-xs-4">
                                        <label for="inputApaterno">Ap. Paterno</label>
                                        <input type="text" class="form-control upperClass" autocomplete="off"  name="inputApaterno" id="inputApaterno" placeholder="Apellido Paterno" value="<?php echo @$this->data['APATERNO']; ?>" disabled>
                                    </div>
                                    <div class="form-group col-xs-4">
                                        <label for="inputAmaterno">Ap. Materno</label>
                                        <input type="text" class="form-control upperClass" autocomplete="off"  name="inputAmaterno" id="inputAmaterno" placeholder="Apellido Materno" value="<?php echo @$this->data['AMATERNO']; ?>" disabled>
                                    </div>
                                </div>

                                <div class="col-xs-12">
                                    <div class="form-group col-xs-4">
                                        <label for="inputNombre">Usuario (E-mail)</label>
                                        <input type="text" class="form-control" autocomplete="off"  name="inputUsuario" id="inputUsuario" placeholder="Usuario" value="<?php echo @$this->data['NICKNAME']; ?>" disabled>
                                    </div>
                                    <div class="form-group col-xs-4">
                                        <label for="inputPhone">Teléfono</label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-phone"></i>
                                            </div>                            
                                            <input type="text" class="form-control upperClass col-xs-4" autocomplete="off"  name="inputPhone" id="inputPhone" placeholder="Teléfono" value="<?php echo @$this->data['TELEFONO']; ?>" disabled>
                                        </div>
                                    </div>                            
                                    <div class="form-group col-xs-4">
                                        <label for="inputTaxip">¿Taxi Propio?</label>
                                        <div class="input-group col-xs-12">                     
                                            <select class="form-control" id="inputTaxip" name="inputTaxip" disabled>
                                                <option value="">Seleccione una opción</option>
                                                <?php echo $this->taxpropio;?>                                
                                            </select>
                                        </div>
                                    </div>                               
                                </div>                        
                            <h4>Información del Taxi</h4>
                            <div class="col-xs-12">
                                <div class="form-group col-xs-4">
                                    <label for="inputNombre">Marca</label>
                                    <div class="input-group col-xs-12">                     
                                        <select class="form-control upperClass" id="inputMarca" autocomplete="off"  name="inputMarca" onChange="getoptionsCbo('Modelo','modeloe',this.value,'','');" disabled>
                                            <option value="">Seleccione una opción</option>
                                            <?php echo $this->aMarcas;?>                                
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-xs-4">
                                    <label for="inputApaterno">Modelo</label>
                                    <div class="input-group col-xs-12">      
                                        <div id="divModelo">
                                            <select class="form-control upperClass" name="inputModelo" id="inputModelo" disabled >
                                                <option value="">Seleccionar una opción</option>
                                                <?php echo $this->aModelos;  ?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group col-xs-4">
                                    <label for="inputAmaterno">Color</label>
                                    <div class="input-group col-xs-12">                     
                                        <select class="form-control upperClass" id="inputColor" name="inputColor" disabled>
                                            <option value="">Seleccione una opción</option>
                                            <?php echo $this->aColores;?>                                
                                        </select>
                                    </div>
                                </div>                                  
                            </div>
                            <div class="col-xs-12">
                                <div class="form-group col-xs-4">
                                    <label for="inputNombre">Placas</label>
                                    <input type="text" class="form-control upperClass" name="inputPlacas" autocomplete="off"  id="inputPlacas" placeholder="Placas" value="<?php echo @$this->dataTaxi['PLACAS']; ?>" disabled>
                                </div>                                        
                                <div class="form-group col-xs-4">
                                    <label for="inputApaterno">Eco</label>
                                    <input type="text" class="form-control upperClass" name="inputEco" autocomplete="off"  id="inputEco" placeholder="ECO" value="<?php echo @$this->dataTaxi['ECO']; ?>" disabled>
                                </div>                                
                                <div class="form-group col-xs-4">
                                    <label for="inputNombre">Año</label>
                                    <input type="text" class="form-control upperClass" name="inputAno" autocomplete="off"  id="inputAno" placeholder="Año" value="<?php echo @$this->dataTaxi['ANIO']; ?>" disabled>
                                </div>
                            </div>
                            <h4>Asignar Empresa</h4>
                            <div class="col-xs-12">
                                <div class="form-group col-xs-4">
                                    <label for="inputAmaterno">Empresa</label>
                                    <div class="input-group col-xs-12">                     
                                        <select class="form-control upperClass" id="inputEmpresa" name="inputEmpresa">
                                            <option value="">Seleccione una opción</option>
                                            <?php echo $this->aEmpresas;?>                                
                                        </select>
                                    </div>
                                </div>                                 
                            </div>  
                        </div>

                        <div class="box-footer col-xs-12">                                                                                    
                            <button type="submit" class="btn btn-primary pull-right margin-5">Enviar Asignación</button>
                            <button type="button" onClick="declineData()" class="btn btn-warning pull-right margin-5">Rechazar Solicitud</button>
                        </div>
                    </form>   
                </div>
            </div><!-- /.box -->
        </div>
    </section><!-- /.content -->