<?php $this->headScript()->appendFile('/js/jquery.countdown360.js'); ?>
<?php $this->headScript()->appendFile('/controllers/callcenter/services/js/serviceinfo.js') ?>

    <section class="content-header no-margin">
        <h1 class="text-center">
            <a class="pull-left" href="/callcenter/client/clientinfo?strClient=<?php echo @$this->aDataViaje['ID_CLIENTE'];?>">
                <i class="fa fa-arrow-circle-left"></i> Regresar
            </a>            
            Información del Viaje
            <medium>#<?php echo $this->idViaje;?></medium>
            <small class="pull-right">Estatus: <?php echo $this->aDataViaje['ESTATUS'];?></small>
        </h1>
    </section> 

    <input type="hidden" id="idViaje" name="idViaje" value="<?php echo $this->aDataViaje['ID_VIAJES'];?>"/>
    <input type="hidden" id="inputEstatus"      name="inputEstatus"    value="<?php echo @$this->aDataViaje['ID_SRV_ESTATUS'];  ?>">
    <input type="hidden" id="inputLatOrigen"    name="inputLatOrigen"  value="<?php echo @$this->aDataViaje['ORIGEN_LATITUD'];  ?>">
    <input type="hidden" id="inputLonOrigen"    name="inputLonOrigen"  value="<?php echo @$this->aDataViaje['ORIGEN_LONGITUD'];  ?>">
    <input type="hidden" id="inputLatDestino"   name="inputLatDestino" value="<?php echo @$this->aDataViaje['DESTINO_LATITUD']; ?>">
    <input type="hidden" id="inputLonDestino"   name="inputLonDestino" value="<?php echo @$this->aDataViaje['DESTINO_LONGITUD']; ?>">
    <input type="hidden" id="inputDistancia" name="inputDistancia" value="<?php echo @$this->aDataViaje['DISTANCIA_VIAJE']; ?>">
    <input type="hidden" id="inputTiempo"    name="inputTiempo"    value="<?php echo @$this->aDataViaje['TIEMPO_VIAJE']; ?>">   


    <input type="hidden" id="inputULastLat" name="inputULastLat" value="<?php echo @$this->aLastPosition['LATITUD']; ?>">
    <input type="hidden" id="inputULastLon" name="inputULastLon" value="<?php echo @$this->aLastPosition['LONGITUD']; ?>">                             

    <section class="content">
        <div class="row">
            <div class="col-md-4 p-right-0">
                <div class="box box-solid">
                    <div class="box-header bg-aqua font-white">
                        <i class="fa fa-info-circle"></i>
                        <h3 class="box-title">Información del Viaje</h3>
                    </div>
                    <div class="box-body row-min-h200">
                        <table class="table table-bordered table-striped">
                            <tr>
                                <td>Estatus</td>
                                <td><?php echo $this->aDataViaje['ESTATUS'];?></td>
                            </tr>                             
                            <tr>
                                <td>Id del Viaje</td>
                                <td><?php echo $this->aDataViaje['ID_VIAJES'];?></td>
                            </tr>

                            <tr>
                                <td>Fecha Viaje</td>
                                <td><?php echo $this->aDataViaje['FECHA_VIAJE'];?></td>
                            </tr>

                            <tr>
                                <td>Distancia Aproximada</td>
                                <td><?php echo $this->aDataViaje['DISTANCIA_VIAJE'];?> kms.</td>
                            </tr>   
                            <tr>
                                <td>Tiempo Estimado del Viaje</td>
                                <td><?php echo $this->aDataViaje['TIEMPO_VIAJE'];?></td>
                            </tr>                            
                        </table>
                    </div>                
                </div>    
                <div class="box box-solid">
                    <div class="box-header bg-yellow font-white">
                        <i class="fa fa-truck"></i>
                        <h3 class="box-title">Taxi</h3>
                    </div>
                    <div class="box-body row-min-h200">                    
                        <?php if($this->aDataViaje['ID_SRV_ESTATUS']==-1 || $this->aDataViaje['ID_SRV_ESTATUS']==1 ||
                                 $this->aDataViaje['ID_SRV_ESTATUS']== 6 || $this->aDataViaje['ID_SRV_ESTATUS']==7):?>
                            
                            <input type="hidden" id="inputTaxi" value="<?php echo (isset($this->aDataViaje['ID_TAXISTA'])) ? '1': '0';?>"/>                                            
                            <?php if($this->aDataViaje['SEG_DIF']<300):?>

                                <?php if (!isset($this->aDataViaje['ID_TAXISTA'])):?>
                                        <div id="divOptions" style="display:<?php echo (isset($this->aDataViaje['ID_TAXISTA'])) ? 'none': 'block';?>; text-align:center">
                                            <h3> Esperando Respuesta del Taxi </h3>
                                                <address>
                                                    <div id="countdown" class="countdownService" ></div>
                                                </address>
                                        </div>        
                                        <!--<div id="divOptionsRenew" style="display:<?php echo (isset($this->aDataViaje['ID_TAXISTA'])) ? 'block': 'none';?>; text-align:center;">-->
                                        <div id="divOptionsRenew" style="display:block; text-align:center;">
                                            <form role="form" id="FormData" method="POST" action="/callcenter/services/serviceinfo">
                                                <input  type="hidden" id="inputOpr" name="optReg" value="renew" />                        
                                                <input  type="hidden" id="strViaje" name="strViaje" value="<?php echo $this->aDataViaje['ID_VIAJES'];?>"/>
                                                <button type="submit" class="btn btn-primary" data-dismiss="modal">Volver a Solicitar</button>
                                            </form>
                                        </div>                                        
                                    <?php endif;?>
                                
                            <?php else:?>
                                
                                <div style="text-align:center;">
                                    <h3>Sin Taxi Asignado</h3> 
                                </div>
                                <div id="divOptionsRenew" style="display:<?php echo (isset($this->aDataViaje['ID_TAXISTA'])) ? 'none': 'block';?>; text-align:center;">
                                    <form role="form" id="FormData" method="POST" action="/callcenter/services/serviceinfo">
                                        <input  type="hidden" id="inputOpr" name="optReg" value="renew" />                        
                                        <input  type="hidden" id="strViaje" name="strViaje" value="<?php echo $this->aDataViaje['ID_VIAJES'];?>"/>
                                        <button type="submit" class="btn btn-primary" data-dismiss="modal">Volver a Solicitar</button>
                                    </form>
                                </div>                                   
                            <?php  endif;?> 
                        <?php else:?>
                            <table class="table table-bordered table-striped">
                                <?php if($this->aDataViaje['ID_SRV_ESTATUS']==2):?>
                                    <tr>
                                        <td>Tiempo Estimado de arribo</td>
                                        <td><span id="spanCalcTime">Calculando...</span></td>
                                    </tr>                                    
                                <?php endif;?>
                                <tr>
                                    <td>Clave Viaje</td>
                                    <td><?php echo (isset($this->aDataViaje['ID_TAXISTA'])) ? $this->aDataViaje['CLAVE_VIAJE'] : 'Sin Taxi Asignado';?></td>
                                </tr>
                                <tr>
                                    <td>Taxista</td>
                                    <td>
                                <dd><?php echo (isset($this->aDataViaje['ID_TAXISTA'])) ? $this->aDataViaje['TAXISTA'] : 'Sin Taxi Asignado';?></td>
                                </tr>

                                <tr>
                                    <td>Taxi</td>
                                    <td><?php echo (isset($this->aDataViaje['ID_TAXISTA'])) ? $this->aDataViaje['TAXI'] : 'Sin Taxi Asignado';?></td>
                                </tr>
                            </table>                            

                        <?php endif;?>                      
                    </div>
                </div>                
            </div>
            <div class="col-md-8">
                <div class="box box-solid">                
                    <!--<div class="box-header bg-yellow font-white">
                        <i class="fa fa-map-marker"></i>
                        <h3 class="box-title"></h3>
                    </div>-->
                    <div class="box-body row-min-h200">
                        <table class="table table-bordered table-striped">
                            <tr>
                                <td><img src="/images/assets/origen.png" width="15px"/></td>
                                <td>Origen</td>
                                <td><?php echo $this->aDataViaje['ORIGEN'];?></td>
                            </tr> 
                            <?php if(isset($this->aDataViaje['ORIGEN_REFERENCIAS']) && $this->aDataViaje['ORIGEN_REFERENCIAS']!=""):?>
                                <tr>
                                    <td colspan="2">Referencias</td>
                                    <td><?php echo $this->aDataViaje['ORIGEN_REFERENCIAS'];?></td>
                                </tr>
                            <?php endif;?>                            
                            <tr>
                                <td><img src="/images/assets/destino.png"  width="15px"/></td>
                                <td>Destino</td>
                                <td><?php echo $this->aDataViaje['DESTINO'];?></td>
                            </tr> 
                             <?php if(isset($this->aDataViaje['DESTINO_REFERENCIAS']) && $this->aDataViaje['DESTINO_REFERENCIAS']!=""):?>
                                <tr>
                                    <td colspan="2">Referencias</td>
                                    <td><?php echo $this->aDataViaje['DESTINO_REFERENCIAS'];?></td>
                                </tr>
                            <?php endif;?>                                                         
                        </table>
                        <br/>
                        <div id="myMapDraw" style="width:100%;height:400px;">

                        </div>
                        <div class="count-down-map">
                            <div id="countdownTrace" style="display:none;"></div>
                        </div>                        
                    </div>
                
                </div>
            </div>            
        </div>    
        
        <?php $result = '';?>
        <?php foreach($this->recorrido as $key => $items): ?>        
            <?php $result .= ($result!="") ? "!" : "";?>
            <?php $result .= $items['LATITUD']."|".$items['LONGITUD']."|".$items['FECHA']."|".
                    $items['UBICACION']."|".round($items['VELOCIDAD'],2)."|".round($items['ANGULO'],2);?>
        <?php  endforeach;?>
        <div id="positions" class="hide"><?php echo $result; ?></div> 
    </section>

<div class="modal fade" id="ModalConfirm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Taxistas no disponibles</h4>
            </div>
                <div class="modal-body">
                    <span>Por el momento no hay taxis disponibles. 
                        Indicar al cliente, que en un momento se pondra en contacto con el, para confirmar el servicio.
                    </span>
                </div>
                <div class="modal-footer clearfix">                     
                    <button type="button" class="btn btn-primary pull-left" data-dismiss="modal">Cerrar</button>
                </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ModalIncidencia" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Incidencia</h4>
            </div>
                <div class="modal-body">
                    <img id="loader1" class="col-xs-offset-4" src="/images/assets/loading.gif" alt="loading gif"/>
                    <iframe class="hmodal550" id="iFrameInc" src="" style="zoom:0" frameborder="0"></iframe>
                </div>
                <!--<div class="modal-footer clearfix">                     
                    <button type="button" class="btn btn-primary pull-left" data-dismiss="modal">Cerrar</button>
                </div>-->
        </div>
    </div>
</div>