<?php $this->headScript()->appendFile('/controllers/gralFunctions.js') ?>
<?php $this->headScript()->appendFile('/js/jasny-bootstrap.min.js') ?>
<?php $this->headScript()->appendFile('/js/plugins/daterangepicker/daterangepicker.js') ?>
<?php echo $this->headLink()->appendStylesheet('/css/jasny-bootstrap.min.css'); ?>
<?php $this->headScript()->appendFile('/controllers/admin/js/validateTaxi.js') ?>
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>
<input id="hRefLinkMain" type="hidden" value="/admin/cars/index" />

    <section class="content">
        <div id="divAlert" class="alert alert-danger alert-dismissable hide">
            <i class="fa fa-ban"></i>
            <b>!Atención¡</b>
            <div id="divErrorContent">                
            </div>
        </div>

        <div class="col-xs-12">
          <div class="box box-primary row-min-h800">
            <div class="box-header">
                <h3 class="box-title">Nuevo Taxi</h3>
            </div>
            <form role="form" method="POST" action="/admin/cars/getinfo" id="FormData" enctype="multipart/form-data">
                <input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
                <input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />

                <div class="col-xs-3">
                    <div class="fileinput fileinput-new" data-provides="fileinput">
                      <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                            <img height="210" src="<?php echo $this->BaseUrl; ?>/main/image/index?img=./images/taxis/<?php echo (isset($this->data['IMAGEN']) && $this->data['IMAGEN']!="") ? $this->data['IMAGEN']: "no_disponible.jpg"; ?>&height=250&width=280&relatio=false" class="">
                      </div>
                      <div>
                        <span class="btn btn-default btn-file">
                        <span class="fileinput-new">Seleccionar Imagen</span>
                        <span class="fileinput-exists">Cambiar</span>
                        <input type="file" name="imageProfile"></span>
                        <a href="#" class="btn btn-default fileinput-exists col-xs-12" data-dismiss="fileinput">Eliminar</a>
                      </div>
                    </div>

                    <div class="<?php echo (isset($this->errors['errorImage'])) ? 'div-border-error': '';?>">
                        <p class="">Formatos permitidos: .png .jpg .jpeg<br/>
                            Tamaño máximo: 10MB
                        </p>
                    </div>
                    <div class="form-group col-xs-12">
                        <label for="inputVin">El Vehículo cuenta con:</label>
                        <div class="controls">
                            <input type="checkbox" onClick="optionAll(this.checked);" <?php echo (@$this->data['AC']==1 && @$this->data['IAVE']==1 && @$this->data['CONECTOR_CELULAR']==1 && @$this->data['WIFI']==1) ? 'checked':'';?>>&nbsp;Todas 
                            <br/>
                            <input name="inputac" class="chkOn" type="checkbox" <?php echo (@$this->data['AC']==1) ? 'checked':'';?>>&nbsp;Aire Acondicionado 
                            <br/>
                            <input name="inputiave"    class="chkOn" type="checkbox" <?php echo (@$this->data['IAVE']==1)? 'checked':'';?>>&nbsp;Tarjeta IAVE
                            <br/>
                            <input name="inputconnect"  class="chkOn" type="checkbox" <?php echo (@$this->data['CONECTOR_CELULAR']==1)? 'checked':'';?>>&nbsp;Cargador Celular
                            <br/>
                            <input name="inputwifi"  class="chkOn" type="checkbox" <?php echo (@$this->data['WIFI']==1)? 'checked':'';?>>&nbsp;Wifi                                 
                        </div>
                    </div>                                                              

                </div>
                <div class="col-xs-9">   
                        <?php if(count(@$this->errors)>0):?>
                         <div class="alert alert-danger alert-dismissable">
                                <i class="fa fa-ban"></i>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <b>!Atención¡</b>
                                <?php if(@$this->errors['errorImage']==1):?>
                                    <div>La imagen no fue posible guardarla, favor de verificar las especificaciones.</div>
                                <?php endif; ?>                                
                            </div>
                        <?php endif;?>

                        <?php if(@$this->resultOp=='okRegister'):?>
                            <div class="alert alert-success alert-dismissable">
                                <i class="fa fa-check"></i>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <b>!Atención¡</b> Los datos se han guardado correctamente.
                            </div>
                        <?php endif;?>                

                        <?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
                            <div id="divAlert" class="alert alert-danger alert-dismissable">
                                <i class="fa fa-ban"></i>
                                <b>!Atención¡</b>
                                <div>Usted no tiene permiso para ver esta información</div>
                            </div>                                      
                        <?php else:?>   
                                <div class="box-body">
                                    <div class="col-xs-12">
                                        <div class="form-group col-xs-6">
                                            <label for="inputSize">Tamaño</label>
                                            <div class="input-group col-xs-12">                     
                                                <select class="form-control" id="inputSize" name="inputSize">
                                                    <option value="">Seleccione una opción</option>
                                                    <?php echo $this->aTIpo;?>                                
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group col-xs-6">
                                            <label for="inputTipo">Tipo</label>
                                            <div class="input-group col-xs-12">                     
                                                <select class="form-control" id="inputTipo" name="inputTipo" onChange="getTarifas();">
                                                    <option value="">Seleccione una opción</option>
                                                    <?php echo $this->aTypes;?>                                
                                                </select>
                                            </div>
                                        </div>                                        
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group col-xs-6">
                                            <label for="inputEstado">Estado</label>
                                            <div class="input-group col-xs-12">                     
                                                <select class="form-control" id="inputEstado" name="inputEstado" onChange="getTarifas();">
                                                    <option value="">Seleccione una opción</option>
                                                    <?php echo $this->aEstados;?>                                
                                                </select>
                                            </div>
                                        </div>                                        
                                        <div class="form-group col-xs-6">
                                            <label for="inputTarifa">Tarifa</label>
                                            <div class="input-group col-xs-12"> 
                                                <div id="divTarifa">
                                                    <select class="form-control" id="inputTarifa" name="inputTarifa" >
                                                        <option value="">Seleccione una opción</option>
                                                        <?php echo $this->aTarifas;?>                                
                                                    </select>    
                                                </div>                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group col-xs-6">
                                            <label for="inputNombre">Marca</label>
                                            <div class="input-group col-xs-12">                     
                                                <select class="form-control upperClass" id="inputMarca" name="inputMarca" onChange="getoptionsCbo('Modelo','modeloe',this.value,'','');">
                                                    <option value="">Seleccione una opción</option>
                                                    <?php echo $this->aMarcas;?>                                
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group col-xs-6">
                                            <label for="inputApaterno">Modelo</label>
                                            <div class="input-group col-xs-12">      
                                                <div id="divModelo">
                                                    <select class="form-control upperClass" name="inputModelo" id="inputModelo" <?php echo $disabled;?> >
                                                        <option value="">Seleccionar una opción</option>
                                                        <?php echo $this->aModelos;  ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group col-xs-6">
                                            <label for="inputAmaterno">Color</label>
                                            <div class="input-group col-xs-12">                     
                                                <select class="form-control upperClass" id="inputColor" name="inputColor" >
                                                    <option value="">Seleccione una opción</option>
                                                    <?php echo $this->aColores;?>                                
                                                </select>
                                            </div>
                                        </div>           

                                        <div class="form-group col-xs-6">
                                            <label for="inputNombre">Año</label>
                                            <input type="text" class="form-control upperClass" name="inputAno" id="inputAno" placeholder="Año" value="<?php echo @$this->data['ANIO']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group col-xs-6">
                                            <label for="inputNombre">Placas</label>
                                            <input type="text" class="form-control upperClass" name="inputPlacas" id="inputPlacas" placeholder="Placas" value="<?php echo @$this->data['PLACAS']; ?>">
                                        </div>                                        
                                        <div class="form-group col-xs-6">
                                            <label for="inputApaterno">Eco</label>
                                            <input type="text" class="form-control upperClass" name="inputEco" id="inputEco" placeholder="ECO" value="<?php echo @$this->data['ECO']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group col-xs-6">
                                            <label for="inputVigencia">Vigencia Seguro</label>
                                            <input type="text" class="form-control upperClass" name="inputVigencia" id="inputVigencia" placeholder="Inicio Vigencia" value="<?php echo @$this->data['VIGENCIA_SEGURO']; ?>" readonly>
                                        </div>             
                                        <div class="form-group col-xs-6">
                                            <label for="inputVin">VIN</label>
                                            <input type="text" class="form-control upperClass" name="inputVin" id="inputVin" placeholder="VIN" value="<?php echo @$this->data['VIN']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-xs-12">                                       
                                        <div class="form-group col-xs-6">
                                            <label for="inputPhone">Estatus</label>
                                            <div class="input-group col-xs-12">                     
                                                <select class="form-control" id="inputEstatus" name="inputEstatus" >
                                                    <option value="">Seleccione una opción</option>
                                                    <?php echo $this->aStatus;?>                                
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group col-xs-6">
                                            <label for="inputAmaterno">Nombre Chofer</label>
                                            <input type="text" class="form-control upperClass" name="inputChofer" id="inputChofer" placeholder="Nombre del Chofer" value="<?php echo @$this->data['NOMBRE_CHOFER']; ?>">
                                        </div>                                                                                                                       
                                    </div>                                                             
                                </div><!-- /.box-body -->

                        <?php endif;?>
                </div>  
                <div class="col-xs-12">
                    <h4>Documentación</h4>
                </div>
                <div class="col-xs-12">

                    <div class="col-md-3">
                        <span><b>Tarjeta de Circulación (Frente)</b></span>
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <div style="height:40px;">
                                <?php if(@$this->data['VAL_TCIRCULACION']==3 ):?>
                                    <span style="color:red;"><small>El documento fue rechazado, favor de volverlo a enviar.</small></span>
                                <?php elseif(@$this->data['VAL_TCIRCULACION']==2 ):?>
                                    <span style="color:green;"><small>El documento ha sido aceptado.</small></span>
                                <?php elseif(@$this->data['VAL_TCIRCULACION']==1 ):?>
                                    <span style="color:gray;"><small>El documento se encuentra en proceso de validación.</small></span>
                                <?php endif;?>      
                            </div>                                        

                            <?php if(@$this->data['VAL_TCIRCULACION']==1 ):?>
                              <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                                    <img height="210" src="<?php echo $this->BaseUrl; ?>/main/image/index?img=./images/documentacion/wait.gif&height=250&width=280&relatio=false" class="">
                              </div>
                            <?php elseif(@$this->data['VAL_TCIRCULACION']==2 ):?>
                              <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                                    <img height="210" src="/images/documentacion/aprovado.png" class="">
                              </div>
                            <?php else:?>
                              <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                                <img height="210" src="<?php echo $this->BaseUrl; ?>/main/image/index?img=./images/documentacion/<?php echo (isset($this->data['IMAGEN_TCIRCULACION']) && $this->data['IMAGEN_TCIRCULACION']!="") ? $this->data['IMAGEN_TCIRCULACION']: "no_disponible.jpg"; ?>&height=250&width=280&relatio=false" class="">
                              </div>                                        
                              <div>
                                <span class="btn btn-default btn-file">
                                <span class="fileinput-new">Seleccionar Imagen</span>
                                <span class="fileinput-exists">Cambiar</span>
                                <input type="file" name="imageTcirculacion" accept=".png,.jpg,jpeg,.pdf"  onchange="checkfileImages(this);" ></span>
                                <a href="#" class="btn btn-default fileinput-exists col-xs-12" data-dismiss="fileinput">Eliminar</a>
                              </div>
                            <?php endif;?>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <span><b>Tarjeta de Circulación (Reverso)</b></span>
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <div style="height:40px;">
                                <?php if(@$this->data['VAL_TCIRCULACION_2']==3 ):?>
                                    <span style="color:red;"><small>El documento fue rechazado, favor de volverlo a enviar.</small></span>
                                <?php elseif(@$this->data['VAL_TCIRCULACION_2']==2 ):?>
                                    <span style="color:green;"><small>El documento ha sido aceptado.</small></span>
                                <?php elseif(@$this->data['VAL_TCIRCULACION_2']==1 ):?>
                                    <span style="color:gray;"><small>El documento se encuentra en proceso de validación.</small></span>
                                <?php endif;?>      
                            </div>                                        

                            <?php if(@$this->data['VAL_TCIRCULACION_2']==1 ):?>
                              <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                                    <img height="210" src="<?php echo $this->BaseUrl; ?>/main/image/index?img=./images/documentacion/wait.gif&height=250&width=280&relatio=false" class="">
                              </div>
                            <?php elseif(@$this->data['VAL_TCIRCULACION_2']==2 ):?>
                              <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                                    <img height="210" src="/images/documentacion/aprovado.png" class="">
                              </div>
                            <?php else:?>
                              <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                                <img height="210" src="<?php echo $this->BaseUrl; ?>/main/image/index?img=./images/documentacion/<?php echo (isset($this->data['IMAGEN_TCIRCULACION_2']) && $this->data['IMAGEN_TCIRCULACION_2']!="") ? $this->data['IMAGEN_TCIRCULACION_2']: "no_disponible.jpg"; ?>&height=250&width=280&relatio=false" class="">
                              </div>                                        
                              <div>
                                <span class="btn btn-default btn-file">
                                <span class="fileinput-new">Seleccionar Imagen</span>
                                <span class="fileinput-exists">Cambiar</span>
                                <input type="file" name="imageTbcirculacion" accept=".png,.jpg,jpeg,.pdf"  onchange="checkfileImages(this);" ></span>
                                <a href="#" class="btn btn-default fileinput-exists col-xs-12" data-dismiss="fileinput">Eliminar</a>
                              </div>
                            <?php endif;?>
                        </div>
                    </div>                    

                    <div class="col-md-3">
                        <span><b>Imagen Factura</b></span>
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <div style="height:40px;">
                                <?php if(@$this->data['VAL_FACTURA']==3 ):?>
                                    <span style="color:red;"><small>El documento fue rechazado, favor de volverlo a enviar.</small></span>
                                <?php elseif(@$this->data['VAL_FACTURA']==2 ):?>
                                    <span style="color:green;"><small>El documento ha sido aceptado.</small></span>
                                <?php elseif(@$this->data['VAL_FACTURA']==1 ):?>
                                    <span style="color:gray;"><small>El documento se encuentra en proceso de validación.</small></span>
                                <?php endif;?>      
                            </div>                                        

                            <?php if(@$this->data['VAL_FACTURA']==1 ):?>
                              <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                                    <img height="210" src="<?php echo $this->BaseUrl; ?>/main/image/index?img=./images/documentacion/wait.gif&height=250&width=280&relatio=false" class="">
                              </div>
                            <?php elseif(@$this->data['VAL_FACTURA']==2 ):?>
                              <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                                    <img height="210" src="/images/documentacion/aprovado.png" class="">
                              </div>
                            <?php else:?>
                              <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                                <img height="210" src="<?php echo $this->BaseUrl; ?>/main/image/index?img=./images/documentacion/<?php echo (isset($this->data['IMAGEN_FACTURA']) && $this->data['IMAGEN_FACTURA']!="") ? $this->data['IMAGEN_FACTURA']: "no_disponible.jpg"; ?>&height=250&width=280&relatio=false" class="">
                              </div>                                        
                              <div>
                                <span class="btn btn-default btn-file">
                                <span class="fileinput-new">Seleccionar Imagen</span>
                                <span class="fileinput-exists">Cambiar</span>
                                <input type="file" name="imageFactura" accept=".png,.jpg,jpeg,.pdf"  onchange="checkfileImages(this);" ></span>
                                <a href="#" class="btn btn-default fileinput-exists col-xs-12" data-dismiss="fileinput">Eliminar</a>
                              </div>
                            <?php endif;?>
                        </div>
                    </div> 
       

                    <div class="col-md-3">
                        <span><b>Imagen Póliza de Seguro</b></span>
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <div style="height:40px;">
                                <?php if(@$this->data['IMAGEN_POLIZA']==3 ):?>
                                    <span style="color:red;"><small>El documento fue rechazado, favor de volverlo a enviar.</small></span>
                                <?php elseif(@$this->data['IMAGEN_POLIZA']==2 ):?>
                                    <span style="color:green;"><small>El documento ha sido aceptado.</small></span>
                                <?php elseif(@$this->data['IMAGEN_POLIZA']==1 ):?>
                                    <span style="color:gray;"><small>El documento se encuentra en proceso de validación.</small></span>
                                <?php endif;?>      
                            </div>                                        

                            <?php if(@$this->data['IMAGEN_POLIZA']==1 ):?>
                              <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                                    <img height="210" src="<?php echo $this->BaseUrl; ?>/main/image/index?img=./images/documentacion/wait.gif&height=250&width=280&relatio=false" class="">
                              </div>
                            <?php elseif(@$this->data['IMAGEN_POLIZA']==2 ):?>
                              <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                                    <img height="210" src="/images/documentacion/aprovado.png" class="">
                              </div>
                            <?php else:?>
                              <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 165px; height: 150px;">
                                <img height="210" src="<?php echo $this->BaseUrl; ?>/main/image/index?img=./images/documentacion/<?php echo (isset($this->data['IMAGEN_POLIZA']) && $this->data['IMAGEN_POLIZA']!="") ? $this->data['IMAGEN_POLIZA']: "no_disponible.jpg"; ?>&height=250&width=280&relatio=false" class="">
                              </div>                                        
                              <div>
                                <span class="btn btn-default btn-file">
                                <span class="fileinput-new">Seleccionar Imagen</span>
                                <span class="fileinput-exists">Cambiar</span>
                                <input type="file" name="imagepoliza" accept=".png,.jpg,jpeg,.pdf"  onchange="checkfileImages(this);" ></span>
                                <a href="#" class="btn btn-default fileinput-exists col-xs-12" data-dismiss="fileinput">Eliminar</a>
                              </div>
                            <?php endif;?>
                        </div>
                    </div>                                                          
                </div>                

                <div class="box-footer col-xs-12">                                                        
                    <button type="button" class="btn pull-right margin-5" onClick="javascript:backToMain()">Cancelar</button>
                    <button type="submit" class="btn btn-primary pull-right margin-5">Guardar</button>
                </div>

                </form>
            </div><!-- /.box -->
        </div>
    </section><!-- /.content -->         