<?php $this->headScript()->appendFile('/js/bootstrap-slider.js'); ?> 
<?php $this->headScript()->appendFile('/js/jquery.countdown360.js'); ?> 
<?php $this->headScript()->appendFile('/controllers/admin/js/rastreoTaxis.js'); ?>
<?php $control=0?>
<div id="divDataPersonal" class="hide">
    <?php foreach($this->aTaxistas as $key => $items):?><?php echo ($control==0) ? '': '?';?><?php echo $items['ID_USUARIO']."|".$items['NOMBRE']."|".$items['N_TAXI'];?><?php $control++;?><?php endforeach;?>
</div>


<aside class="right-side">
    <section class="content">
        <div class="col-md-4 ">
            <div class="box box-solid row-min-h650">
                <div class="box-header">
                    <i class="fa fa-users"></i>
                    <h3 class="box-title">Taxistas</h3>           
                </div>
                <div class="box-body chart-responsive">
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                        <thead>
                            <tr>
                                <th style="width:10px;"><input type="checkbox" name="inputAllCheck" id="inputAllCheck" onClick="optionAll(this.checked);"/></th>
                                <th>Taxista</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>                                
                            
                        </tbody>
                    </table>                    
                </div>
            </div>
        </div> 

        <div class="col-md-8">
            <div class="box box-solid row-min-h650">
                <div class="box-header">
                    <i class="fa fa-map-marker"></i>
                    <h3 class="box-title">Mapa</h3>                   
                </div>
                <div class="box-body chart-responsive">
                    <div id="Map" style="width:100%;height:550px;"></div>  
                    <div class="">
                        <div class="span12">
                            <div id="countdown" ></div>
                                <div id="divSliderC" style="display:none;" class="pull-right p-10">
                                    <div class="muted pull-left">Intervalo de Actualización <b><span id="labelMinutes">60 </span> segs.</b></div>
                                    <div class="col-md-4">                 
                                        <input id="slideTimeUp" data-slider-id='ex1Slider' type="text" data-slider-min="10" data-slider-max="120" data-slider-step="1" data-slider-value="60"/>
                                    </div> 
                                </div>                                
                        </div>                        
                    </div>    
                </div>
            </div>
        </div>
    </section>
</aside>


<div class="modal fade hide modal-lg" id="myModalMapa" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" ></h4>
        </div>
      <div class="modal-form i-body">             
        <iframe class="hmodal550" id="iFrameModalMapa" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>  
