<?php $this->headScript()->appendFile('/controllers/admin/js/reporteRastreo.js'); ?>
<body class="skin-yellow fixed bg-white">
    <section class="">    	
		<div class="">
            <div class="box box-solid">
                <form role="form" id="FormData"  method="POST" action="/admin/rastreo/reporte?strInput=<?php echo $this->data['strInput']; ?>">
					<input type="hidden" name="optReg" value="search" />
					<input type="hidden" id="strInput" name="strInput" value="<?php echo $this->data['strInput']; ?>" />
                    <div class="box-body">                                          
                        <div class="form-group col-xs-3">
                            <label for="inputFindName">Fecha Inicio</label>
                            <input type="text" class="form-control" id="inputFechaIn" name="inputFechaIn" value="<?php echo @$this->data['inputFechaIn']; ?>">
                        </div>
                        <div class="form-group col-xs-3">
                            <label for="inputFindApp">Fecha Final</label>
                            <input type="text" class="form-control" id="inputFechaFin" name="inputFechaFin" value="<?php echo @$this->data['inputFechaFin']; ?>">
                        </div>
                    </div>
                    <div class="box-footer">
                        <button id="btnSearch" type="submit" class="btn btn-primary">
                            <i class="fa fa-search"></i>  Buscar</button>						
                    </div>
                </form>
            <!--</div>

            <div class="box box-solid">  -->              
                <div class="box-body">
					<div class="nav-tabs-custom">						
		                <ul class="nav nav-tabs">
		                    <li class="active"><a href="#mapa" data-toggle="tab">Mapa</a></li>
		                    <li><a href="#tabular" data-toggle="tab">Tabular</a></li>
							<?php if(count($this->aRecorrido)>0):?>
								<div class="pull-right">
									<a target="_blank" href="/admin/rastreo/exportsearch?strInput=<?php echo $this->data['strInput']; ?>&inputFechaIn=<?php echo @$this->data['inputFechaIn'];?>&inputFechaFin=<?php echo @$this->data['inputFechaFin'];?>"><button class="btn btn-success"><i class="fa fa-file-text-o"></i> Exportar </button></a>								
								</div>								
							<?php endif;?>			                    
		                </ul>
		                <div class="tab-content">
		                    <div class="tab-pane active" id="mapa">
								<div id="Map" style="width:98%;height:350px;"></div>
		                    </div>
		                    <div class="tab-pane " id="tabular">	                    	
								<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered"  id="dataTable">
									<thead>				
									    <tr>
									        <th>Fecha GPS</th>
									        <th>Tipo</th>
									        <th>Latitud</th>
									        <th>Longitud</th>
									        <th>Velocidad</th>
									        <th>Ubicación</th>
									    </tr>
									</thead>
									<tbody>
										<?php $result = '';?>
										<?php foreach($this->aRecorrido as $key => $items): ?>
											<tr>
												<td><?php echo $items['FECHA_GPS'];?></td>
												<td><?php echo $items['PROVEEDOR'];?></td>
												<td><?php echo $items['LATITUD'];?></td>
												<td><?php echo $items['LONGITUD'];?></td>
												<td><?php echo round($items['VELOCIDAD'],2);?> kms/h.</td>
												<td><?php echo $items['UBICACION'];?></td>
											</tr>
											<?php $result .= ($result!="") ? "!" : "";?>
											<?php $result .= $items['ID_USUARIO']."|".
															 $items['FECHA_GPS']."|".
															 $items['PROVEEDOR']."|".
															 $items['LATITUD']."|".
															 $items['LONGITUD']."|".
															 round($items['VELOCIDAD'],2)."|".
															 $items['UBICACION'];?>
										<?php  endforeach;?>
									</tbody>
								</table>
								<div id="positions" class="hide"><?php echo $result; ?></div>                         
		                    </div>
		                </div>
		            </div>
                </div>
            </div>
		</div>
    </section>
</body>