<?php $this->headScript()->appendFile('/controllers/login/js/login.js') ?>
<div class="form-box" id="login-box">
    <div class="header">
        <a href="/">
            <img src="/images/assets/icon-page.png" class="img-responsive center-block" alt="Logo">
        </a>
    </div>

    <form rol="form">
        <div id="div-msg" class="alert alert-danger" style="display:none">
            
        </div>
        <div class="body bg-gray">
            <div class="form-group has-error">
                <label id="lbl_user" class="control-label" for="inputError" style="display:none"><i class="fa fa-times-circle-o"></i>Usuario requerido</label>
                <input id="txt-user" type="text" name="userid" class="form-control" placeholder="Usuario"/>
            </div>

            <div class="form-group has-error">
                <label id="lbl_pass" class="control-label" for="inputError" style="display:none"><i class="fa fa-times-circle-o"></i>Contraseña requerida</label>
                <input id="txt-pass"  type="password" name="password" class="form-control" placeholder="Contraseña"/>
            </div>
            <!--<div class="form-group">
                <input type="checkbox" name="remember_me"/> Recordar Datos
            </div>-->
        </div>
        <div class="footer">                                                               
            <button onclick="validatelogin();" type="button" class="btn bg-black btn-block">Ingresar</button>
        </div>
    </form>
</div>