<?php $this->headScript()->appendFile('/controllers/login/js/recovery.js') ?>
    <div class="login-box">
        <div class="login-logo">
          <a href="/">
              <img src="/images/assets/icon-page.png" class="img-responsive center-block" alt="Logo">
          </a>
        </div><!-- /.login-logo -->              
      <div class="login-box-body box_body_login">
        <p class="login-box-msg">Recuperar Contraseña</p>
        <?php if(@$this->aErrors['eUsuario']):?>
            <div class="alert alert-danger" style="display:block;">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <h4>Error</h4>
              <div>El usuario no se encuentra registrado, favor de contactar con su adminsitrador.</div>
            </div>
        <?php endif;?>

        <?php if(@$this->resultOp=='okRegister'):?>
            <div class="alert alert-success alert-dismissable">
                <i class="fa fa-check"></i>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <b>!Atención¡</b> Se ha enviado un correo electrónico, favor de verificar su bandeja de entrada.<br/>
                Tambien es recomendable verificar en la carpeta de Spam (Correo no deseado).
            </div>
        <?php endif;?>   
        <form role="form" method="POST" action="/login/main/recovery" id="FormData" >
            <input type="hidden" name="optReg" value="<?php echo ($this->optRegister>0) ? 'rememeber': '';?>" />
            <div id="formg-user" class="form-group has-feedback">
                <label  id="lbl_user"  class="control-label" for="txt-user"  style="display:none"><i class="fa fa-times-circle-o"></i>Usuario requerida</label>
                <input type="text" class="form-control" id="inputUser"  name="inputUser"  placeholder="Usuario (E-mail)"/>
                <span class="glyphicon glyphicon-envelope form-control-feedback margin-top-0"></span>
            </div>          
            <div class="row  p-10">
                <div class="col-xs-12">
                  <button type="submit" class="btn btn-primary btn-block btn-flat btn_yellow">Recuperar</button>
                </div><!-- /.col -->     
                <div class="col-xs-12 margin-t10px">
                   <a href="/login/main/index" type="button" class="btn btn-primary btn-block btn-flat btn_yellow">Regresar</a>
                </div>                                           
            </div>
        </form>
      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->