<?php $this->headScript()->appendFile('/controllers/login/js/resetPass.js') ?>
    <div class="login-box">
        <div class="login-logo">
          <a href="/">
              <img src="/images/assets/icon-page.png" class="img-responsive center-block" alt="Logo">
          </a>
        </div><!-- /.login-logo -->              
          <div class="login-box-body box_body_login">
            <p class="login-box-msg">Guardar Nueva Contraseña</p>
            <?php if(@$this->aErrors['errorConfig']):?>
                <div class="alert alert-danger" style="display:block;">
                  <button type="button" class="close" data-dismiss="alert">×</button>
                  <h4>Error</h4>
                  <div>Información recibida incorrecta, favor de contactar con su adminsitrador.</div>
                </div>

                <form role="form" >
                    <div class="row  p-10">
                        <div class="col-xs-12 margin-t10px">
                           <a href="/login/main/index" type="button" class="btn btn-primary btn-block btn-flat btn_yellow">Regresar</a>
                        </div>                                           
                    </div>
                </form>                
            <?php endif;?>    

            <?php if($this->result=='updated'):?>
                <div class="alert alert-success alert-dismissable">
                    <i class="fa fa-check"></i>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <b>!Atención¡</b> La contraseña se ha cambiado correctamente.<br/>
                </div>
                <form role="form" >
                    <div class="row  p-10">
                        <div class="col-xs-12 margin-t10px">
                           <a href="/login/main/index" type="button" class="btn btn-primary btn-block btn-flat btn_yellow">Ingresar al Sistema</a>
                        </div>                                           
                    </div>
                </form>                    
            <?php elseif(!isset($this->aErrors['errorConfig'])):?>            
                <form role="form" method="POST" action="/login/main/recoverresq?keyResetToker=<?php echo ($this->dataIn['keyResetToker']);?>" id="FormData" >
                    <input type="hidden" name="idReset" value="<?php echo ($this->catId);?>" />
                    <input type="hidden" name="optReg"  value="reset" />

                    <div id="formg-user" class="form-group has-feedback">
                        <label  id="lbl_user"  class="control-label" for="txt-user"  style="display:none"><i class="fa fa-times-circle-o"></i>Contraseña requerida</label>
                        <input type="password" class="form-control" id="inputPassword"  name="inputPassword"  placeholder="Contraseña"/>
                        <span class="glyphicon glyphicon-lock form-control-feedback margin-top-0"></span>
                    </div>    

                    <div id="formg-d" class="form-group has-feedback">
                        <label  id="lbl_user"  class="control-label" for="txt-user"  style="display:none"><i class="fa fa-times-circle-o"></i>Confirmar Contraseña</label>
                        <input type="password" class="form-control" id="inputPassword"  name="inputPassword"  placeholder="Confirmar Contraseña"/>
                        <span class="glyphicon glyphicon-lock form-control-feedback margin-top-0"></span>
                    </div>                                             
                    <div class="row  p-10">
                        <div class="col-xs-12">
                          <button type="submit" class="btn btn-primary btn-block btn-flat btn_yellow">Guardar</button>
                        </div><!-- /.col -->                        
                    </div>
                </form>
            <?php endif;?>
        </div>
    </div>  