<?php $this->headScript()->appendFile('/controllers/main/validateRegisterUser.js') ?>    
<?php $this->headScript()->captureStart() ?>
  window.fbAsyncInit = function() {
    FB.init({
          appId      : '445290902345421',
          xfbml      : true,
          version    : 'v2.4'
        });

     FB.getLoginStatus(function(response) {
        statusChangeCallback(response)
      });                           
  };

  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/es_LA/sdk.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
<?php $this->headScript()->captureEnd() ?>
<div id="fb-root"></div>
    <?php if(count(@$this->errors)>0):?>
        <?php if(@$this->errors['eUsuario']==1):?>
            <div id="divAlert" class="alert alert-danger alert-dismissable">
                <i class="fa fa-ban"></i>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <b>!Atención Error¡</b>
                <div>                
                    El usuario ya se encuentra registrado, favor de verificarlo.
                </div>
            </div>  
        <?php elseif(@$this->errors['status']==1):?>
            <div id="divAlert" class="alert alert-danger alert-dismissable">
                <i class="fa fa-ban"></i>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <b>!Atención Error¡</b>
                <div>                
                    Ocurrio un error en el registro, favor de intentarlo mas tarde.
                </div>
            </div>          
        <?php endif;?>    
    <?php endif; ?>
    <?php if(@$this->resultOp=='okRegisterMail'):?>
        <div class="col-xs-10 col-xs-offset-1">
            <!--
            <div class="login-logo">
              <a href="/">
                  <img alt="Logo" class="img-responsive center-block" src="/images/assets/icon-page.png">
              </a>
            </div>-->
            <div class="login-box-body box_body_login row-min-h500" style="text-align:center;">
                <h2>Bienvenido</h2>
                <h3>
                    Gracias por registrarse en taccsi</span>
                    
                </h3>
                <br/>
                <div class="col-xs-12">                    
                    <!--<div class="col-xs-7">
                        <img src="/images/assets/page.png" class="col-xs-10">
                    </div>-->
                    <div class="col-xs-12" style="text-align:center;">
                        <h2>Descarga la app</h2>
                        <p> Desde ahora podra solicitar un taccsi donde se encuentre.</p>
                        <div class="col-xs-12">
                            <a href="/login/main/index">
                                <img src="/images/assets/esAppStore.png"/></a>
                            </a>
                            &nbsp;&nbsp;
                            <a href="/login/main/index">
                                <img src="/images/assets/esGooglePlay.png"/></a>
                            </a>                            
                        </div>                        
                    </div>
                    <div class="col-xs-12" style="text-align:center;">
                        <div class="col-xs-5" style="margin-left: 30%;margin-top: 5%;">
                          <a href="/" type="button" class="btn btn-primary btn-block btn-flat btn_yellow">Continuar</a>
                        </div>                       
                    </div>
                </div>
            </div>
        </div>
    <?php else:?>   
    <div class="login-box">
        <!--<div class="login-logo">
          <a href="/">
              <img src="/images/assets/icon-page.png" class="img-responsive center-block" alt="Logo">
          </a>
        </div>-->    
        <div class="login-box-body box_body_login">
            <p class="login-box-msg">Registrate para comenzar a viajar</p>
            <p class="login-box-msg" id="box_login">
                <a href="javascript:loginRegister();">
                    <img src="/images/assets/registrate_fbc.png" class="col-xs-11 col-xs-offset-1"/>
                </a>
                <br/>
                <br/>
            </p>  
            <p class="login-box-msg"></p>

            <form role="form" method="POST" action="/main/registeruser/index" id="FormData" enctype="multipart/form-data">
                <input type="hidden" name="optReg" value="opRegister" />

                <div class="form-group col-xs-12 col-offset-12">
                    <!--<label for="inputNombre2">Nombre</label>-->
                    <input type="text" class="form-control upperClass h-50"  autocomplete="off"  name="inputNombre" id="inputNombre" placeholder="Nombre(s)" value="<?php echo @$this->data['inputNombre']; ?>">
                </div>
                <div class="form-group col-xs-12">
                    <!--<label for="inputNombre2">Apellido Paterno</label>-->
                    <input type="text" class="form-control upperClass h-50" autocomplete="off"  name="inputApaterno" id="inputApaterno" placeholder="Apellido Paterno" value="<?php echo @$this->data['inputApaterno']; ?>">
                </div>
                <div class="form-group col-xs-12">
                    <!--<label for="inputNombre2">Apellido Materno</label>-->
                    <input type="text" class="form-control upperClass h-50" autocomplete="off"  name="inputAmaterno" id="inputAmaterno" placeholder="Apellido Materno" value="<?php echo @$this->data['inputAmaterno']; ?>">
                </div>
                <div class="form-group col-xs-12">
                    <!--<label for="inputNombre2">Usuario (E-mail)</label>-->
                    <input type="text" class="form-control h-50" autocomplete="off"  name="inputUsuario" id="inputUsuario" placeholder="Usuario (E-mail)" value="<?php echo @$this->data['inputUsuario']; ?>">
                </div>
                <div class="form-group col-xs-12">
                    <!--<label for="inputNombre2">Movil</label>-->
                    <input type="text" class="form-control upperClass col-xs-4 h-50" autocomplete="off"  name="inputPhone" id="inputPhone" placeholder="Movil" value="<?php echo @$this->data['inputPhone']; ?>">
                </div>     
                <div class="form-group col-xs-12">
                    <!--<label for="inputNombre2">RFC</label>-->
                     <input type="password" class="form-control h-50" autocomplete="off"  name="inputPassword" id="inputPassword" placeholder="Contraseña" value="<?php echo @$this->data['inputPassword']; ?>">
                </div>
                <div class="form-group col-xs-12">
                    <!--<label for="inputNombre2">Contraseña</label>-->                    
                    <input type="password" class="form-control h-50" autocomplete="off"  name="inputCpassword" id="inputCpassword" placeholder="Confirmar Contraseña" value="<?php echo @$this->data['inputCpassword']; ?>">
                </div>
                  <div class="row  p-10">
                    <div class="col-xs-12">
                      <button type="submit" class="btn btn-primary btn-block btn-flat btn_yellow">Enviar</button>
                    </div>
                    <div class="col-xs-12 margin-t10px">
                       <a href="/" type="button" class="btn btn-primary btn-block btn-flat btn_yellow">Regresar</a>
                    </div>                    
                  </div>
                </form>
            </div>      
        </div>            
    <?php endif;?>      